Repository programminghistorian/jekyll, pull requests merged in 2018-04, with the labels that each got.

#774 use snippets to implement language-specific title quoting
  _data/snippets.yml
  _layouts/lesson.html
Labels: technical

#775 Issue #687 - Indian blog post
  _posts/2018-04-04-programming-historian-india
  images/programming-historian-india/programming-historian-india.png
Labels: outreach

#780 Display translation date on lesson header
  Gemfile.lock
  _data/snippets.yml
  _layouts/lesson.html
Labels: technical, translation

#784 Translation link
  _data/snippets.yml
  _layouts/lesson.html
Labels: technical, translation

#804 correct wrong translation date
  es/lecciones/introduccion-control-versiones-github-desktop.md
Labels: spanish

#803 Create 2018-04-16-programming-historian-community-survey.md
  _posts/2018-04-16-programming-historian-community-survey.md
Labels: outreach

#806 Correct R code typo in "Tabular Data" lesson
  lessons/r-basics-with-tabular-data.md
Labels: bug

#813 Set titles of es about & index pages to Spanish
  es/acerca-de.md
  es/index.md
Labels: bug
