Repository programminghistorian/jekyll, pull requests merged in 2018-10, with the labels that each got.

#1036 XSL Lesson edit
  en/lessons/transforming-xml-with-xsl.md
  es/lecciones/transformacion-datos-xml-xsl.md
Labels: bug

#1044 Translate treasurer and sponsorship coord roles
  _data/teamroles.yml
Labels: spanish, translation

#1049 bundle update
  Gemfile.lock
Labels: technical

#1048 Add alert bar to wget lesson re: Nat Arch. Australia
  en/lessons/applied-archival-downloading-with-wget.md
Labels: bug

#1052 Fix twitter cards
  _includes/twitter-card.html
Labels: bug, technical

#1055 Markdownify abstracts
  _includes/lesson_describe.html
  _layouts/lesson.html
  doaj_xml/doaj.xml
  en/lessons/json-and-jq.md
Labels: bug

#1058 Correct broken link in Unity retirement alert
  en/lessons/retired/intro-to-augmented-reality-with-unity.md
Labels: bug
