Repository programminghistorian/jekyll, pull requests merged in 2018-09, with the labels that each got.

#1008 New page of lessons we'd like to see
  _data/snippets.yml
  _includes/menu.html
  en/lesson-requests.md
Labels: enhancement, translation

#999 Shorten Editorial Guidelines - Issue 992
  en/editor-guidelines.md
  es/guia-editor.md
Labels: translation

#1029 Links to images should be https
  _plugins/validate_yaml.rb
  en/lessons/getting-started-with-markdown.md
  en/lessons/intro-to-beautiful-soup.md
  es/lecciones/introduccion-a-markdown.md
Labels: bug, technical

#1014 Change references from current GH desktop to GHD "classic"
  en/lessons/getting-started-with-github-desktop.md
  es/lecciones/introduccion-control-versiones-github-desktop.md
Labels: bug, translation

#998 New lesson template to Author Guidelines #991
  en/author-guidelines.md
Labels: translation

#1031 Bundle update
  .gitignore
  .ruby-version
  Gemfile.lock
Labels: technical
