Repository programminghistorian/jekyll, pull requests merged in 2018-06, with the labels that each got.

#881 menu link to technical contributions wiki
  _data/snippets.yml
  _includes/menu.html
Labels: outreach, technical

#859 Check absolute links
  Gemfile.lock
  _plugins/validate_yaml.rb
  _posts/2014-11-05-how-we-moved-to-github.md
  _posts/2018-05-22-Uses-Of-The-Programming-Historian.md
  en/author-guidelines.md
  en/editor-guidelines.md
  en/feedback.md
  en/lessons/mapping-with-python-leaflet.md
  es/guia-editor.md
  es/lecciones/introduccion-a-markdown.md
  es/retroalimentacion.md
Labels: technical

#883 add new translation on linked data
  es/lecciones/introduccion-datos-abiertos-enlazados.md
  images/intro-to-linked-data/intro-a-datos-enlazados-fig5.png
  images/intro-to-linked-data/intro-a-datos-enlazados-fig6.png
Labels: spanish, translation

#882 add new translation on powershell
  es/lecciones/introduccion-a-powershell.md
Labels: spanish, translation

#913 repair markdown links that had extra whitespace
  es/acerca-de.md
  es/guia-para-autores.md
  es/lecciones/editar-audio-con-audacity.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
Labels: bug

#912 Display multiple ISSN on footer
  _data/snippets.yml
  _includes/footer.html
  en/about.md
  es/acerca-de.md
Labels: technical

#925 fix two internal links in Spanish guidelines for authors and translators
  es/guia-para-autores.md
Labels: bug, spanish

#922 add new translation on r
  es/lecciones/procesamiento-basico-de-textos-en-r.md
  images/basic-text-processing-in-r/longitud-de-oraciones-linea.jpg
  images/basic-text-processing-in-r/longitud-de-oraciones.jpg
  images/basic-text-processing-in-r/numero-de-palabras-y-tipo.jpg
  images/basic-text-processing-in-r/numero-de-palabras.jpg
Labels: spanish
