Repository programminghistorian/jekyll, pull requests merged in 2018-12, with the labels that each got.

#1111 Update new translated lesson: descarga-automatizada-con-wget.md
  es/lecciones/descarga-automatizada-con-wget.md
Labels: spanish, translation

#1119 Update procesamiento-basico-de-textos-en-r.md closes #1118
  es/lecciones/procesamiento-basico-de-textos-en-r.md
Labels: spanish, technical

#1120 better author name matching for avatar photos
  _data/ph_authors.yml
  _includes/contact-info.html
  _posts/2017-03-14-matthew-lincoln.md
  _posts/2017-03-30-two-new-PH-editors.md
  _posts/2018-02-13-jennifer-isasi-jose-a-motilla.md
  _posts/2018-05-24-anna-maria-sichani.md
  _posts/2018-07-13-FR-team.md
  _posts/2018-11-09-welcome-zoe-leblanc.md
  avatars/adam-crymble.png
  avatars/alan-maceachern.png
  avatars/allison-hegel.png
  avatars/amanda-visconti.png
  avatars/anandi-silva-knuppel.png
  avatars/andrew-hnatow.png
  avatars/anna-maria-sichani.png
  avatars/antonio-rojas-castro.png
  avatars/brandon-walsh.png
  avatars/caleb-mcdaniel.png
  avatars/carrie-sanders.png
  avatars/daniel-van-strien.png
  avatars/douglas-duhaime.png
  avatars/evan-taparata.png
  avatars/francois-dominic-laramee.png
  avatars/fred-gibbs.png
  avatars/ian-milligan.png
  avatars/james-baker.png
  avatars/jennifer-isasi.png
  avatars/jeremy-boggs.png
  avatars/jeri-wieringa.png
  avatars/jessica-parr.png
  avatars/jose-antonio-motilla.png
  avatars/kim-pham.png
  avatars/maria-jose-afanador-llach.png
  avatars/maria-velez-serna.png
  avatars/marie-puren.png
  avatars/matthew-lincoln.png
  avatars/miriam-posner.png
  avatars/sofia-papastamkou.png
  avatars/stephen-margheim.png
  avatars/taryn-dewar.png
  avatars/victor-gayol.png
  avatars/william-j-turkel.png
  avatars/zoe-leblanc.png
Labels: bug, technical

#1099 Create 2018-11-27-ad-hoc-translation
  _posts/2018-11-30-ad-hoc-translation.md
Labels: outreach

#1128 Blogpost absolute link check
  _plugins/validate_yaml.rb
  _posts/2018-07-09-PH-espanol-in-DH2018.md
  _posts/2018-07-13-FR-team.md
  _posts/2018-10-06-convocatoria-para-editores.md
  _posts/2018-11-30-ad-hoc-translation.md
Labels: bug, technical

#1133 Update data_wrangling_and_management_in_R.md
  en/lessons/data_wrangling_and_management_in_R.md
Labels: bug, english

#1134 Update guia-editor.md
  es/guia-editor.md
Labels: spanish
