Repository programminghistorian/jekyll, pull requests merged in 2018-05, with the labels that each got.

#800 Replace Unity lesson
  lessons/retired/intro-to-augmented-reality-with-unity.md
Labels: bug, review

#818 Language links refactor
  Gemfile.lock
  _config.yml
  _data/snippets.yml
  _includes/author-info.html
  _includes/figure.html
  _includes/header.html
  _includes/lesson-slug.html
  _includes/lesson_describe.html
  _includes/menu.html
  _includes/page-slug.html
  _includes/translation-links.html
  _layouts/base.html
  _layouts/blank.html
  _layouts/lesson.html
  _plugins/validate_yaml.rb
  es/acerca-de.md
  es/contribuciones.md
  es/equipo-de-proyecto.md
  es/guia-editor.md
  es/guia-para-autores.md
  es/guia-para-revisores.md
  es/index.md
  es/investigacion.md
  es/lecciones.md
  es/lecciones/contar-frecuencias.md
  es/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas.md
  es/lecciones/crear-y-ver-archivos-html-con-python.md
  es/lecciones/de-html-a-lista-de-palabras-1.md
  es/lecciones/de-html-a-lista-de-palabras-2.md
  es/lecciones/editar-audio-con-audacity.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
  es/lecciones/instalacion-linux.md
  es/lecciones/instalacion-mac.md
  es/lecciones/instalacion-windows.md
  es/lecciones/instalar-modulos-python-pip.md
  es/lecciones/intro-a-google-maps-y-google-earth.md
  es/lecciones/introduccion-a-bash.md
  es/lecciones/introduccion-a-markdown.md
  es/lecciones/introduccion-control-versiones-github-desktop.md
  es/lecciones/introduccion-e-instalacion.md
  es/lecciones/limpieza-de-datos-con-OpenRefine.md
  es/lecciones/manipular-cadenas-de-caracteres-en-python.md
  es/lecciones/mineria-de-datos-en-internet-archive.md
  es/lecciones/normalizar-datos.md
  es/lecciones/palabras-clave-en-contexto-n-grams.md
  es/lecciones/poniendo-omeka-a-funcionar.md
  es/lecciones/preservar-datos-de-investigacion.md
  es/lecciones/reutilizacion-de-codigo-y-modularidad.md
  es/lecciones/salida-de-datos-como-archivo-html.md
  es/lecciones/salida-palabras-clave-contexto-ngrams.md
  es/lecciones/sparql-datos-abiertos-enlazados.md
  es/lecciones/trabajar-con-archivos-de-texto.md
  es/lecciones/trabajar-con-paginas-web.md
  es/lecciones/ver-archivos-html.md
  es/politica-retirada-lecciones.md
  es/retroalimentacion.md
  translation-concordance.md
Labels: technical, translation

#824 Language link match fix
  _includes/menu.html
  _includes/translation-links.html
  _layouts/lesson.html
  lessons/fetch-and-parse-data-with-openrefine.md
Labels: bug

#828 Incorporate Lessons into RSS Feed
  _includes/feed-item.html
  es/lecciones/introduccion-a-bash.md
  es/lecciones/poniendo-omeka-a-funcionar.md
  feed.xml
Labels: enhancement

#839 add new translation on antconc
  es/lecciones/analisis-de-corpus-con-antconc.md
Labels: spanish

#842 Update references to font awesome
  _includes/contact-info.html
Labels: bug

#861 Update Membership History
  _data/ph_authors.yml
Labels: bug

#865 adding post on anna maria sichani
  _posts/2018-05-24-anna-maria-sichani.md
Labels: outreach

#873 french logo to /_promo
  _promo/programmingHistorianFR.jpg
Labels: french

#875 Display translation review link
  _layouts/lesson.html
Labels: bug
