Repository programminghistorian/jekyll, pull requests merged in 2018-11, with the labels that each got.

#1035 Add Treasurer and Sponsorship roles
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: finance, policy, translation

#1078 Create favicon
  favicon.ico
Labels: bug, technical

#1085 Start ES volume numbering from 2017
  _data/snippets.yml
Labels: bug

#1092 Typo fixes for jq lesson
  en/lessons/creating-mobile-augmented-reality-experiences-in-unity.md
  en/lessons/json-and-jq.md
  en/lessons/retired/intro-to-augmented-reality-with-unity.md
Labels: bug
