Repository programminghistorian/jekyll, pull requests merged in 2019-06, with the labels that each got.

#1322 several typos
  es/lecciones/introduccion-a-powershell.md
Labels: spanish

#1334 add aria roles to navigation dropdowns
  _includes/menu.html
  css/style.css
Labels: technical

#1353 add privacy policy
  _data/snippets.yml
  _includes/menu.html
  en/privacy-policy.md
Labels: english

#1363 Xampp link fix
  _posts/2018-05-22-Uses-Of-The-Programming-Historian.md
  en/lessons/introduction-to-populating-a-website-with-api-data.md
Labels: bug

#1342 Technical team and technical lead role
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: technical, translation
