Repository programminghistorian/jekyll, pull requests merged in 2019-10, with the labels that each got.

#1479 use pipe syntax for yaml abstracts
  en/editor-guidelines.md
  es/guia-editor.md
  fr/consignes-redacteurs.md
Labels: bug, technical

#1481 Update basic-text-processing-in-r.md
  en/lessons/basic-text-processing-in-r.md
Labels: bug

#1470 Update lesson extracting-keywords from Python 2 to Python 3.
  en/lessons/extracting-keywords.md
Labels: bug

#1494 From HTML to list of words 2 - python3
  en/lessons/from-html-to-list-of-words-2.md
  es/lecciones/de-html-a-lista-de-palabras-2.md
Labels: english, spanish

#1493 Html to list of Words - 1 (ES/EN)
  en/lessons/from-html-to-list-of-words-1.md
  es/lecciones/de-html-a-lista-de-palabras-1.md
Labels: english, spanish

#1499 Add avatar and bio to site
  _data/ph_authors.yml
  avatars/sarah-melton.png
Labels: english

#1495 Working with webpages python3
  en/lessons/working-with-web-pages.md
  es/lecciones/trabajar-con-paginas-web.md
Labels: english, spanish

#1505 Retire GH desktop lessons
  en/lessons/retired/getting-started-with-github-desktop.md
  es/lecciones/retirada/introduccion-control-versiones-github-desktop.md
  es/politica-retirada-lecciones.md
Labels: bug, english, spanish, technical

#1490 Issue 1460 transliterating
  en/lessons/transliterating.md
Labels: english

#1517 Output Keywords in Context in HTML file to python3
  en/lessons/output-keywords-in-context-in-html-file.md
Labels: english

#1507 update python zip files to v3
  assets/python-lessons1.zip
  assets/python-lessons2.zip
  assets/python-lessons3.zip
  assets/python-lessons4.zip
  assets/python-lessons5.zip
  assets/python-lessons6.zip
  assets/python-lessons7.zip
  assets/python-lessons8.zip
  assets/python-lessons9.zip
Labels: english

#1516 ngrams lesson to Python3
  en/lessons/keywords-in-context-using-n-grams.md
Labels: english

#1509 Normalizing Data - Python3
  en/lessons/normalizing-data.md
Labels: english

#1511 Counting Frequencies to Python3
  en/lessons/counting-frequencies.md
Labels: english

#1513 Remove python2 warning
  en/lessons/code-reuse-and-modularity.md
  en/lessons/creating-and-viewing-html-files-with-python.md
  en/lessons/manipulating-strings-in-python.md
  en/lessons/working-with-text-files.md
  es/lecciones/crear-y-ver-archivos-html-con-python.md
  es/lecciones/manipular-cadenas-de-caracteres-en-python.md
  es/lecciones/trabajar-con-archivos-de-texto.md
Labels: english, spanish
