Repository programminghistorian/jekyll, pull requests merged in 2019-09, with the labels that each got.

#1415 updates to beautiful soup tutorial to address issues from #1347.
  en/lessons/intro-to-beautiful-soup.md
  en/lessons/transforming-xml-with-xsl.md
  es/lecciones/transformacion-datos-xml-xsl.md
Labels: bug

#1435 Create comprendre-les-pages-web.md
  fr/lecons/comprendre-les-pages-web.md
Labels: french, translation

#1436 fixes misspelling
  en/lessons/introduction-to-stylometry-with-python.md
Labels: english

#1445 remove Marie Puren from Team listing.
  _data/ph_authors.yml
Labels: Team Development

#1447 Create 2019-09-11-call-for-fr-members - closes #1428
  _posts/2019-09-11-call-for-fr-members.md
Labels: french

#1455 take away Marie's name as mediator in the FR guidelines
  fr/consignes-auteurs.md
  fr/consignes-evaluateurs.md
  fr/consignes-redacteurs.md
  fr/consignes-traducteurs.md
Labels: french

#1444 Add explainer re relationship between the Programming Historian and ProgHist Ltd
  _data/snippets.yml
  _includes/footer.html
  en/about.md
  es/acerca-de.md
  fr/apropos.md
Labels: Team Development

#1472 Newsletter 2 (sept. 2019)
  _posts/2019-09-30-bolentin-informativo.md
  _posts/2019-09-30-buletin-de-information.md
  _posts/2019-09-30-newsletter.md
  images/blog/ach-2019-presentation.jpg
  images/blog/dh-2019-poster.JPG
Labels: Communication
