Repository programminghistorian/jekyll, pull requests merged in 2019-07, with the labels that each got.

#1364 Added privacy policy in Spanish
  _data/snippets.yml
  es/politica-de-privacidad.md
Labels: policy, spanish

#1361 2019 Mid Year Newsletter
  _posts/2019-06-30-boletin-informativo.md
  _posts/2019-06-30-buletin-de-information.md
  _posts/2019-06-30-mid-year-newsletter.md
Labels: Communication

#1369 Upload note about Premios HDH 2018
  _posts/2019-07-09-premio-hdh-2018.md
Labels: Communication, spanish

#1366 Create analyse-corpus-antconc.md
  fr/lecons/analyse-corpus-antconc.md
Labels: french

#1260 Create translator-guidelines
  en/translator-guidelines.md
Labels: english, french, spanish, translation

#1376 Create Travailler avec des fichiers texte
  _data/ph_authors.yml
  _data/snippets.yml
  _posts/2018-05-22-Uses-Of-The-Programming-Historian.md
  en/lessons/introduction-to-ffmpeg.md
  fr/lecons/travailler-avec-des-fichiers-texte.md
Labels: french, translation

#1398 bad link formatting in newsletter post
  _posts/2019-06-30-buletin-de-information.md
Labels: bug
