Repository programminghistorian/jekyll, pull requests merged in 2019-03, with the labels that each got.

#1166 Add 'Support Us' to top menu
  _data/snippets.yml
  _includes/menu.html
  es/acerca-de.md
  es/apoyanos.md
  fr/apropos.md
  fr/nous-soutenir.md
Labels: finance, french, spanish, translation

#1197 Metadata spacing
  _includes/footer.html
  _layouts/lesson.html
  css/style.css
Labels: bug, technical

#1219 Update FR team roles in relevant pages
  _data/ph_authors.yml
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/Formulario.Consulta.Leccion.txt
  assets/forms/Lesson.Query.Form.txt
  en/lessons/qgis-layers.md
  en/project-team.md
  es/equipo-de-proyecto.md
  fr/consignes-auteurs.md
  fr/consignes-evaluateurs.md
  fr/consignes-redacteurs.md
  fr/contribuer.md
  fr/equipe-projet.md
Labels: french

#1229 Managing editor yaml
  _data/snippets.yml
  _includes/managing-editor-loop.html
  _includes/managing-editor.html
  en/author-guidelines.md
  en/contribute.md
  en/feedback.md
  en/project-team.md
  en/research.md
  es/contribuciones.md
  es/equipo-de-proyecto.md
  es/guia-para-autores.md
  es/investigacion.md
  fr/consignes-auteurs.md
  fr/contribuer.md
  fr/equipe-projet.md
  fr/reaction.md
  fr/recherche.md
Labels: enhancement, technical

#1212 All pages plugin check
  Gemfile.lock
  _plugins/validate_yaml.rb
  en/about.md
  en/author-guidelines.md
  en/support-us.md
  es/acerca-de.md
  es/apoyanos.md
  es/guia-para-autores.md
  fr/apropos.md
  fr/consignes-auteurs.md
  fr/nous-soutenir.md
Labels: enhancement

#1239 typo on 404 page
  404.md
Labels: bug
