Repository programminghistorian/jekyll, pull requests merged in 2019-11, with the labels that each got.

#1514 convert Output Text as HTML to python3
  en/lessons/output-data-as-html-file.md
Labels: english

#1536 Create beginners guide to twitter data
  _data/ph_authors.yml
  en/lessons/beginners-guide-to-twitter-data.md
  gallery/beginners-guide-to-twitter-data.png
  gallery/originals/beginners-guide-to-twitter-data-original.png
  images/beginners-guide-to-twitter-data/all-values-populated.png
  images/beginners-guide-to-twitter-data/blurred-dataset.png
  images/beginners-guide-to-twitter-data/dataset-selection.png
  images/beginners-guide-to-twitter-data/decrease-decimal.png
  images/beginners-guide-to-twitter-data/dehydrated-IDs.png
  images/beginners-guide-to-twitter-data/doc-now-download.png
  images/beginners-guide-to-twitter-data/downloads.png
  images/beginners-guide-to-twitter-data/exports.png
  images/beginners-guide-to-twitter-data/first-return-value.png
  images/beginners-guide-to-twitter-data/format-as-numbers.png
  images/beginners-guide-to-twitter-data/format-for-vlookup.png
  images/beginners-guide-to-twitter-data/fusion-map.png
  images/beginners-guide-to-twitter-data/hydrated-save-file.png
  images/beginners-guide-to-twitter-data/hydrator-loaded.png
  images/beginners-guide-to-twitter-data/hydrator.png
  images/beginners-guide-to-twitter-data/last-values.png
  images/beginners-guide-to-twitter-data/lookup-value.png
  images/beginners-guide-to-twitter-data/naming-dataset.png
  images/beginners-guide-to-twitter-data/palladio.png
  images/beginners-guide-to-twitter-data/parameters-1.png
  images/beginners-guide-to-twitter-data/parameters-2.png
  images/beginners-guide-to-twitter-data/parameters-3.png
  images/beginners-guide-to-twitter-data/paste-special.png
  images/beginners-guide-to-twitter-data/post-hydration.png
  images/beginners-guide-to-twitter-data/pre-hydration.png
  images/beginners-guide-to-twitter-data/preprocess-edges.png
  images/beginners-guide-to-twitter-data/special-paste-values.png
  images/beginners-guide-to-twitter-data/statistics.png
  images/beginners-guide-to-twitter-data/table-array.png
  images/beginners-guide-to-twitter-data/tableau-map.png
  images/beginners-guide-to-twitter-data/trump-tweets-viz.png
  images/beginners-guide-to-twitter-data/tweet-id-file.png
  images/beginners-guide-to-twitter-data/tweetsets-home.png
  images/beginners-guide-to-twitter-data/vlookup-final.png
  images/beginners-guide-to-twitter-data/vlookup-formula-builder.png
  images/beginners-guide-to-twitter-data/vlookup-search.png
  images/beginners-guide-to-twitter-data/widen-columns.png
  images/beginners-guide-to-twitter-data/zoom-map.png
Labels: english

#1550 Update Jmparr roles
  _data/ph_authors.yml
Labels: english

#1561 fix spelling and add URLs to citations
  en/lessons/sentiment-analysis.md
Labels: english

#1559 update mac IDE to python 3
  en/lessons/mac-installation.md
Labels: english

#1566 Update lesson-template.md
  en/lesson-template.md
Labels: bug

#1565 Added new snippet: rss-feed
  _data/snippets.yml
  _includes/footer.html
Labels: technical
