Repository programminghistorian/jekyll, pull requests merged in 2019-08, with the labels that each got.

#1386 Issue 1367 - New English Author Guidelines (Stylesheet)
  en/author-guidelines.md
  en/lesson-template.md
Labels: english

#1409 blog post advertising ME position
  _posts/2019-08-08-new-English-managing-editor.md
Labels: english

#1375 check that author has bio in the appropriate language
  _data/ph_authors.yml
  _plugins/validate_yaml.rb
  en/lessons/fetch-and-parse-data-with-openrefine.md
Labels: spanish, technical

#1418 Add French rss feed
  feed.xml
Labels: Global Team, bug, french, technical

#1419 Adds note about escaping quotation marks in captions for figures
  en/author-guidelines.md
  es/guia-para-autores.md
  fr/consignes-auteurs.md
Labels: bug, french, spanish, technical

#1422 Update snippets.yml
  _data/snippets.yml
Labels: french, translation

#1427 Update consignes-auteurs.md - closes #1420
  fr/consignes-auteurs.md
Labels: french

#1429 Add a link to ph-submissions on the lesson requests page
  en/lesson-requests.md
  es/solicitud-lecciones.md
Labels: spanish
