Repository programminghistorian/jekyll, pull requests merged in 2019-04, with the labels that each got.

#1262 only load MathJax on pages that need it
  _includes/header.html
  en/lessons/gravity-model.md
  en/lessons/text-mining-with-extracted-features.md
Labels: technical

#1263 publishing nettoyer-ses-donnees-avec-openrefine lesson in FR
  _data/ph_authors.yml
  _data/snippets.yml
  _includes/french-alert.html
  _includes/homepage_block.html
  _plugins/validate_yaml.rb
  fr/index.md
  fr/lecons.md
  fr/lecons/.keep
  fr/lecons/nettoyer-ses-donnees-avec-openrefine.md
  images/cleaning-data-with-openrefine/vueRegroupementValeurs.png
Labels: french, translation

#1264 create welcome blogpost PH-FR in EN and FR, closes #1161 and #1184
  _posts/2019-08-04-bienvenue-ph-fr.md
  _posts/2019-08-04-welcome-ph-fr.md
  images/welcome-ph-fr/welcome-ph-fr.png
Labels: french, outreach

#1270 fixes date of two welcome blogposts for PH FR
  _posts/2019-04-08-bienvenue-ph-fr.md
  _posts/2019-04-08-welcome-ph-fr.md
Labels: french

#1277 New lesson: Add analisis-voyant-tools
  _data/ph_authors.yml
  assets/analisis-voyant-tools/README.md
  assets/analisis-voyant-tools/corpus_presidentes.zip
  assets/analisis-voyant-tools/corpus_presidentes/2006_ar_kirchner.txt
  assets/analisis-voyant-tools/corpus_presidentes/2006_cl_bachelet.txt
  assets/analisis-voyant-tools/corpus_presidentes/2006_co_uribe.txt
  assets/analisis-voyant-tools/corpus_presidentes/2006_mx_fox.txt
  assets/analisis-voyant-tools/corpus_presidentes/2006_pe_toledo.txt
  assets/analisis-voyant-tools/corpus_presidentes/2007_ar_kirchner.txt
  assets/analisis-voyant-tools/corpus_presidentes/2007_cl_bachelet.txt
  assets/analisis-voyant-tools/corpus_presidentes/2007_co_uribe.txt
  assets/analisis-voyant-tools/corpus_presidentes/2007_mx_calderon.txt
  assets/analisis-voyant-tools/corpus_presidentes/2007_pe_garcia.txt
  assets/analisis-voyant-tools/corpus_presidentes/2008_ar_fernandez.txt
  assets/analisis-voyant-tools/corpus_presidentes/2008_cl_bachelet.txt
  assets/analisis-voyant-tools/corpus_presidentes/2008_co_uribe.txt
  assets/analisis-voyant-tools/corpus_presidentes/2008_mx_calderon.txt
  assets/analisis-voyant-tools/corpus_presidentes/2008_pe_garcia.txt
  assets/analisis-voyant-tools/corpus_presidentes/2009_ar_fernandez.txt
  assets/analisis-voyant-tools/corpus_presidentes/2009_cl_bachelet.txt
  assets/analisis-voyant-tools/corpus_presidentes/2009_co_uribe.txt
  assets/analisis-voyant-tools/corpus_presidentes/2009_mx_calderon.txt
  assets/analisis-voyant-tools/corpus_presidentes/2009_pe_garcia.txt
  assets/analisis-voyant-tools/corpus_presidentes/2010_ar_fernandez.txt
  assets/analisis-voyant-tools/corpus_presidentes/2010_cl_pinera.txt
  assets/analisis-voyant-tools/corpus_presidentes/2010_co_uribe.txt
  assets/analisis-voyant-tools/corpus_presidentes/2010_mx_calderon.txt
  assets/analisis-voyant-tools/corpus_presidentes/2010_pe_garcia.txt
  assets/analisis-voyant-tools/stopwords-es.txt
  es/lecciones/analisis-voyant-tools.md
  gallery/analisis-voyant-tools.png
  images/analisis-voyant-tools/1_descargar_archivos.png
  images/analisis-voyant-tools/cargar.png
  images/analisis-voyant-tools/cirrus.png
  images/analisis-voyant-tools/contextos.png
  images/analisis-voyant-tools/datos_archivo_de_texto.png
  images/analisis-voyant-tools/editar_lista.png
  images/analisis-voyant-tools/editarlista.png
  images/analisis-voyant-tools/exportar_contextos.png
  images/analisis-voyant-tools/frecuencia_relativa.png
  images/analisis-voyant-tools/guardar-en-utf8-mac.gif
  images/analisis-voyant-tools/guardar-en-utf8-ubuntu.gif
  images/analisis-voyant-tools/guardar-en-utf8.gif
  images/analisis-voyant-tools/lector.png
  images/analisis-voyant-tools/lista_ruido.png
  images/analisis-voyant-tools/log.png
  images/analisis-voyant-tools/matrimonio.png
  images/analisis-voyant-tools/palabrascontexto.png
  images/analisis-voyant-tools/posicion.png
  images/analisis-voyant-tools/regla-de-tres.png
  images/analisis-voyant-tools/sumario.png
  images/analisis-voyant-tools/tendencias.png
  images/analisis-voyant-tools/tf_idf.png
  images/analisis-voyant-tools/voyant_editar.png
Labels: spanish
