Repository programminghistorian/jekyll, pull requests merged in 2020-07, with the labels that each got.

#1826 Update 2020-06-29-plan-s.md
  _posts/2020-06-29-plan-s.md
  en/lessons/sonification.md
Labels: Communication, bug

#1825 Second Newsletter of 2020
  _posts/2020-07-01-boletin-informativo-junio20.md
  _posts/2020-07-01-bulletin-de-information-juin20.md
  _posts/2020-07-01-newsletter-june20.md
  images/blog/cdcs-uk-logo.png
  images/blog/summer.jpg
  images/blog/winter.jpg
Labels: Communication

#1828 Update support-us.md
  en/support-us.md
  es/apoyanos.md
  fr/nous-soutenir.md
Labels: Communication

#1816 Add Zoe to README
  README.md
  en/editor-guidelines.md
  es/README.md
  es/guia-editor.md
  fr/consignes-redacteurs.md
Labels: technical

#1834 Update sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
Labels: bug, english, spanish

#1836 Update to reflect adding SHERPA/RoMEO entry
  _posts/2020-06-29-plan-s.md
Labels: ProgHist Ltd

#1848 Add note on UKWA captures to about page.
  en/about.md
  es/acerca-de.md
  fr/apropos.md
Labels: Communication

#1847 Create "Installer un environnement de développement intégré pour Python (Windows)"
  fr/lecons/installation-windows-py.md
Labels: french, translation

#1843 upload Portuguese logos
  images/logos/ph-pt-url.svg
  images/logos/ph-pt.svg
Labels: portuguese

#1839 Josir Gomes Bio
  _data/ph_authors.yml
  avatars/josir-cardoso-gomes.png
Labels: Global Team, portuguese

#1859 Adding my avatar and bio, closes #1858
  _data/ph_authors.yml
  avatars/aracele-torres.png
Labels: portuguese

#1853 Add pages to footer
  _data/snippets.yml
  _includes/footer.html
  _includes/menu.html
Labels: Communication

#1854 Fix citeproc command
  en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
Labels: bug

#1862 Removing paragraph with broken images/links
  en/lessons/georeferencing-qgis.md
Labels: bug

#1864 Update author-guidelines.md, closes #1863
  en/author-guidelines.md
Labels: enhancement

#1861 Bug fix for Static website with Jekyll & GitHub - Closes #1669
  en/lessons/building-static-sites-with-jekyll-github-pages.md
Labels: bug, english, technical

#1866 Update support-us for broken link
  en/support-us.md
  es/apoyanos.md
  fr/nous-soutenir.md
Labels: Communication, bug

#1869 Issue 1525 Lesson Sequence Reporting
  _data/snippets.yml
  _layouts/lesson.html
  en/lessons/code-reuse-and-modularity.md
  en/lessons/counting-frequencies.md
  en/lessons/creating-and-viewing-html-files-with-python.md
  en/lessons/downloading-multiple-records-using-query-strings.md
  en/lessons/from-html-to-list-of-words-1.md
  en/lessons/from-html-to-list-of-words-2.md
  en/lessons/georeferencing-qgis.md
  en/lessons/googlemaps-googleearth.md
  en/lessons/introduction-and-installation.md
  en/lessons/keywords-in-context-using-n-grams.md
  en/lessons/manipulating-strings-in-python.md
  en/lessons/normalizing-data.md
  en/lessons/output-data-as-html-file.md
  en/lessons/output-keywords-in-context-in-html-file.md
  en/lessons/qgis-layers.md
  en/lessons/vector-layers-qgis.md
  en/lessons/viewing-html-files.md
  en/lessons/working-with-text-files.md
  en/lessons/working-with-web-pages.md
Labels: technical
