Repository programminghistorian/jekyll, pull requests merged in 2020-02, with the labels that each got.

#1651 Moving files for Working with Batches of PDFs
  _data/ph_authors.yml
  en/lessons/extracting-illustrated-pages.md
  en/lessons/working-with-batches-of-pdf-files.md
  gallery/working-with-batches-of-pdf-files.png
  images/working-with-batches-of-pdf-files/working-with-batches-of-pdf-files1.png
  images/working-with-batches-of-pdf-files/working-with-batches-of-pdf-files2.png
Labels: english

#1660 Add review by Daems to research
  en/research.md
  es/investigacion.md
  fr/recherche.md
Labels: Communication

#1647 Create preserver-ses-donnees-de-recherche.md
  en/lessons/installing-omeka.md
  fr/lecons/preserver-ses-donnees-de-recherche.md
Labels: french

#1637 Issue 1621 - reorder Project Team
  _data/ph_authors.yml
  _data/teamroles.yml
  _includes/project-team-loop.html
  en/project-team.md
  es/equipo-de-proyecto.md
  fr/equipe-projet.md
Labels: Team Development, technical

#1644 Create comprendre-les-expressions-regulieres.md
  Gemfile.lock
  _data/ph_authors.yml
  _plugins/validate_yaml.rb
  fr/lecons/comprendre-les-expressions-regulieres.md
Labels: french

#1666 Date format check
  _plugins/validate_yaml.rb
Labels: bug, enhancement, technical

#1665 Create 2020-02-07-welcome-mc-boucher.md
  _posts/2020-02-07-welcome-mc-boucher.md
Labels: Communication

#1667 Issue1652 - consistent labelling of Project Roles
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: Team Development

#1656 Add Institutional Partner Programme text
  en/support-us.md
  es/apoyanos.md
  fr/nous-soutenir.md
Labels: Communication, Team Development

#1678 Revise text for retiring lessons
  en/lesson-retirement-policy.md
  es/politica-retirada-lecciones.md
  fr/politique-retrait-lecons.md
Labels: bug, technical

#1676 remove outdated data from authors.yml
  _data/ph_authors.yml
  en/lessons/research-data-with-unix.md
Labels: Team Development
