Repository programminghistorian/jekyll, pull requests merged in 2020-03, with the labels that each got.

#1689 Create merci blogpost - closes #1631
  _posts/2020-02-26-merci-les-amis.md
  images/blog/rose-bnf-2.jpg
Labels: Communication, french

#1697 Update travailler-avec-des-fichiers-texte.md closes #1611
  fr/lecons/travailler-avec-des-fichiers-texte.md
Labels: bug, french

#1673 Refactor translation link generation
  _includes/menu.html
  _includes/page-slug.html
  _includes/translation-links.html
  _layouts/base.html
  _layouts/lesson.html
  en/lessons/intro-to-bash.md
  en/lessons/temporal-network-analysis-with-r.md
  es/lecciones/analisis-temporal-red.md
  es/lecciones/datos-de-investigacion-con-unix.md
  es/lecciones/introduccion-a-bash.md
  fr/appel-contributions.md
  fr/politique-vie-privee.md
  fr/votre-avis.md
Labels: enhancement, technical

#1699 Change Volunteer/Institutionally Supported tag colour
  _data/ph_authors.yml
  _includes/contact-info.html
Labels: Team Development, technical

#1696 add new ES ombudsperson
  _data/ph_authors.yml
  avatars/silvia-gutierrez-de-la-torre.png
  es/guia-editor.md
  es/lecciones/analisis-voyant-tools.md
Labels: Team Development, spanish

#1709 Issue 1685 - minor tweaks to core wording re "publications"
  en/about.md
  en/author-guidelines.md
  en/contribute.md
  es/acerca-de.md
  fr/apropos.md
Labels: Global Team, ProgHist Ltd

#1717 create search.json template and instances for each lang
  _layouts/search.json
  en/search.json
  es/search.json
  fr/search.json
Labels: technical

#1719 separate language team from editorial role
  _data/ph_authors.yml
  _data/teamroles.yml
  _includes/contact-info.html
  _includes/project-team-loop.html
Labels: Team Development, technical

#1725 Update to team roles
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: Team Development

#1724 Updated my profile
  _build/build.sh
  _data/ph_authors.yml
  en/lessons/geospatial-data-analysis.md
  en/lessons/r-basics-with-tabular-data.md
  es/lecciones/datos-tabulares-en-r.md
Labels: Communication
