Repository programminghistorian/jekyll, pull requests merged in 2020-04, with the labels that each got.

#1728 Newsletter 1st trimester of 2020 as per #1706
  _posts/2020-04-01-boletin-informativo.md
  _posts/2020-04-01-bulletin-de-information.md
  _posts/2020-04-01-newsletter.md
  images/blog/autumn.jpg
  images/blog/spring.jpg
Labels: Communication

#1731 change name on files
  _posts/2018-07-09-PH-espanol-in-DH2018.md
  _posts/2020-04-01-boletin-informativo-march20.md
  _posts/2020-04-01-bulletin-de-information-march20.md
  _posts/2020-04-01-newsletter-march20.md
  es/lecciones/topic-modeling-y-mallet.md
Labels: Communication, technical

#1730 Nueva lección original: construir repositorio de fuentes históricas con Omeka Classic
  _data/ph_authors.yml
  assets/construir-repositorio-de-fuentes/tutorial.sql
  es/lecciones/construir-repositorio-de-fuentes.md
  gallery/construir-repositorio-de-fuentes.png
  gallery/originals/construir-repositorio-de-fuentes-original.png
  images/construir-repositorio-de-fuentes/image_1.3-locale.png
  images/construir-repositorio-de-fuentes/img_1.1-modact.jpg
  images/construir-repositorio-de-fuentes/img_1.1-xampp-dashboard.jpg
  images/construir-repositorio-de-fuentes/img_1.1.jpg
  images/construir-repositorio-de-fuentes/img_1.2-crear-baseddatos.jpg
  images/construir-repositorio-de-fuentes/img_2.1-omeka_mysql_schema.png
  images/construir-repositorio-de-fuentes/img_3.1-omeka_dump_mysql.png
  images/construir-repositorio-de-fuentes/img_3.2-omeka_import_mysql.png
  images/construir-repositorio-de-fuentes/img_4.1-omeka_add_element_type.png
  images/construir-repositorio-de-fuentes/img_4.2-omeka_add_elements.png
  images/construir-repositorio-de-fuentes/img_4.3-omeka_add_elementsnew.png
  images/construir-repositorio-de-fuentes/img_4.4-omeka_add_element_type.png
  images/construir-repositorio-de-fuentes/img_4.5-omeka_metadata_type_element.png
  images/construir-repositorio-de-fuentes/img_5.1-plugins.png
  images/construir-repositorio-de-fuentes/img_6.0-apariencia.png
  images/construir-repositorio-de-fuentes/img_6.1-apariencia.png
  images/construir-repositorio-de-fuentes/img_7.0-plantilla.png
  images/construir-repositorio-de-fuentes/img_7.1-plantilla.png
  images/construir-repositorio-de-fuentes/img_7.2-plantilla_fecha.png
  images/construir-repositorio-de-fuentes/img_7.3-plantilla_fecha_vis.png
  images/construir-repositorio-de-fuentes/img_8.1-omeka_items.png
  images/construir-repositorio-de-fuentes/img_8.2-omeka_items.png
  images/construir-repositorio-de-fuentes/img_8.3-omeka_items.png
  images/construir-repositorio-de-fuentes/img_9.1-omeka_elements_Set.jpg
  images/construir-repositorio-de-fuentes/img_9.2-omeka_opcion-cap.png
Labels: spanish

#1736 Create manipuler-chaines-caracteres-python
  fr/lecons/manipuler-chaines-caracteres-python.md
Labels: french

#1734 Adjust IPP offer
  en/support-us.md
  es/apoyanos.md
  es/lecciones/construir-repositorio-de-fuentes.md
  fr/nous-soutenir.md
Labels: Communication, Team Development

#1740 Create debuter avec markdown
  _data/ph_authors.yml
  es/lecciones/editar-audio-con-audacity.md
  fr/lecons/debuter-avec-markdown.md
Labels: french

#1745 Crossref xml
  Gemfile.lock
  _layouts/crossref.xml
  en/crossref.xml
  es/crossref.xml
  fr/crossref.xml
Labels: technical

#1750 Remove offline archive listing
  archive/2019-10_PH-Archive.txt
  archive/2019-11_PH-Archive.txt
  archive/2019-12_PH-Archive.txt
  archive/2020-02_PH-Archive.txt
  archive/readme.md
Labels: ProgHist Ltd, Team Development

#1741 Update lesson query forms
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/Formulario.Consulta.Leccion.txt
  assets/forms/Lesson.Query.Form.txt
Labels: english, spanish

#1755 Portuguese core configuration
  _config.yml
  _data/snippets.yml
  en/lessons/creating-apis-with-python-and-flask.md
  en/lessons/text-mining-with-extracted-features.md
  feed.xml
  index.md
  pt/about.md
  pt/author-guidelines.md
  pt/contribute.md
  pt/editor-guidelines.md
  pt/feedback.md
  pt/index.md
  pt/lesson-requests.md
  pt/lesson-retirement-policy.md
  pt/lesson-template.md
  pt/lessons/retired/.keep
  pt/licoes.md
  pt/privacy-policy.md
  pt/project-team.md
  pt/research.md
  pt/reviewer-guidelines.md
  pt/search.json
  pt/support-us.md
  pt/translator-guidelines.md
Labels: technical
