Repository programminghistorian/jekyll, pull requests merged in 2020-09, with the labels that each got.

#1887 1842 Ian Milligan returning as ombudsperson
  _data/ph_authors.yml
  en/author-guidelines.md
  en/editor-guidelines.md
  en/reviewer-guidelines.md
  en/translator-guidelines.md
Labels: english

#1889 Update naive-bayesian.md
  en/lessons/naive-bayesian.md
Labels: english

#1890 French Ombudsperson to project team
  _data/ph_authors.yml
  avatars/helene-huet.png
  fr/consignes-auteurs.md
  fr/consignes-evaluateurs.md
  fr/consignes-redacteurs.md
  fr/consignes-traducteurs.md
Labels: french

#1892 additional metadata on Huet
  _data/ph_authors.yml
Labels: french

#1882 Sponsor08 2020
  en/support-us.md
  es/apoyanos.md
  fr/nous-soutenir.md
Labels: ProgHist Ltd

#1893 Joana vieira paulino onboarding
  _data/ph_authors.yml
  avatars/joana-vieira-paulino.png
Labels: portuguese

#1896 adding my bio to ph_authors.yml
  _data/ph_authors.yml
  avatars/alex-wermer-colan.png
Labels: Team Development, translation

#1899 Implement DOI in lesson header per Issue #1860
  _layouts/lesson.html
  images/doi_icon.jpg
Labels: Communication

#1902 IPP Blog post
  _posts/2016-08-25-presentando-al-nuevo-equipo-de-editores-de-contenidos-en-espanol.md
  _posts/2018-05-22-Uses-Of-The-Programming-Historian.md
  _posts/2020-09-19-join-IPP.md
  images/blog/IPP-blog.png
Labels: Communication, ProgHist Ltd

#1904 Blogpost for FR editors
  _posts/2020-09-21-call-for-fr-members.md
Labels: french
