Repository programminghistorian/jekyll, pull requests merged in 2021-10, with the labels that each got.

#2317 Update retroalimentacion.md
  es/retroalimentacion.md
Labels: spanish

#2308 Update intro-to-beautiful-soup.md
  en/lessons/retired/intro-to-beautiful-soup.md
Labels: english

#2318 Update visualizing-with-bokeh.md
  en/lessons/visualizing-with-bokeh.md
Labels: english

#2316 Update clustering-with-scikit-learn-in-python.md
  en/lessons/clustering-with-scikit-learn-in-python.md
Labels: english

#2320 fixing code blocks
  en/lessons/clustering-with-scikit-learn-in-python.md
Labels: enhancement

#2319 Publicar Processamento basico de texto com R
  pt/licoes/processamento-basico-texto-r.md
Labels: translation, portuguese
