Repository programminghistorian/jekyll, pull requests merged in 2021-03, with the labels that each got.

#2062 Add SSI to IPP
  en/supporters.md
  es/colaboradores.md
Labels: Communication, ProgHist Ltd

#2061 New ES translation: "Sitios estáticos con Jekyll y GH pages"
  es/guia-para-autores.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_1.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_10.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_11.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_12.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_2.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_3.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_4.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_5.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_6.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_7.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_8.png
  images/building-static-sites-with-jekyll-github-pages/sitios-estaticos-con-jekyll-y-github-pages_9.png
Labels: spanish

#2070 Delete research.md
  research.md
Labels: portuguese

#2067 Add profile picture
  avatars/antoine-henry.png
Labels: french

#1992 Contrast mode
  _includes/header.html
  _includes/menu.html
  _layouts/base.html
  css/style.css
  en/privacy-policy.md
  js/header_links.js
Labels: technical

#2060 Little precisions in "Setting up Jekyll" with Mac, closes #2059
  en/lessons/building-static-sites-with-jekyll-github-pages.md
Labels: enhancement

#2063 Support translate - French
  .github/workflows/build.yml
  _build/build.sh
  _data/snippets.yml
  _includes/translation-links.html
  en/individual.md
  en/ipp.md
  en/support-us.md
  en/supporters.md
  es/apoyanos.md
  es/colaboradores.md
  es/donaciones.md
  es/pia.md
  fr/dons.md
  fr/nos-soutiens.md
  fr/nous-soutenir.md
  fr/pi.md
  pt/apoie-nos.md
Labels: ProgHist Ltd, french

#2075 3 New ipp members
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: ProgHist Ltd

#2066 Add Antoine Henry
  _data/ph_authors.yml
  avatars/antoine-henry.png
Labels: french

#2073 Ipp middle band
  en/ipp.md
  es/pia.md
  fr/pi.md
Labels: ProgHist Ltd

#2078 Add book & workshop to Research
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: ProgHist Ltd

#2079 Adds Stanford media article to /research
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2080 Transkribus ipp
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: ProgHist Ltd

#1998 Bug feedback pages update
  _data/snippets.yml
  en/feedback.md
  es/retroalimentacion.md
  fr/reaction.md
  pt/contribua.md
  pt/feedback.md
  pt/index.md
  pt/licoes.md
  pt/reportar-um-erro.md
Labels: Communication

#2081 Edit Lux IPP name upon request from C2DH
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: Communication, ProgHist Ltd

#2083 Blog: post convocatoria editores PH en español
  _posts/2021-03-22-convocatoria-editores-2021.md
  images/blog/printing.png
Labels: Communication, spanish

#2088 New ES original lesson: Análisis de sentimientos en R
  assets/galdos_miau.txt
  es/lecciones/analisis-de-sentimientos-r.md
  fr/lecons/intro-aux-bots-twitter.md
  gallery/analisis-de-sentimientos-r.png
  gallery/originals/analisis-de-sentimientos-r-original.jpg
  images/analisis-de-sentimientos-r/miau_barplot.png
  images/analisis-de-sentimientos-r/miau_nube_emociones.png
  images/analisis-de-sentimientos-r/miau_sentimientos.png
Labels: spanish

#2085 PT support us menu updates
  _data/snippets.yml
Labels: portuguese

#2097 Fixes blockquote margins and contrast in nightmode
  css/style.css
Labels: bug

#2095 removing unused redirect_from lessons
  _includes/menu.html
  _includes/translation-links.html
  es/lecciones/analisis-de-corpus-con-antconc.md
  es/lecciones/contar-frecuencias.md
  es/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas.md
  es/lecciones/crear-y-ver-archivos-html-con-python.md
  es/lecciones/de-html-a-lista-de-palabras-1.md
  es/lecciones/de-html-a-lista-de-palabras-2.md
  es/lecciones/editar-audio-con-audacity.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
  es/lecciones/instalacion-linux.md
  es/lecciones/instalacion-mac.md
  es/lecciones/instalacion-windows.md
  es/lecciones/instalar-modulos-python-pip.md
  es/lecciones/intro-a-google-maps-y-google-earth.md
  es/lecciones/introduccion-a-bash.md
  es/lecciones/introduccion-a-markdown.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
  es/lecciones/introduccion-e-instalacion.md
  es/lecciones/limpieza-de-datos-con-OpenRefine.md
  es/lecciones/manipular-cadenas-de-caracteres-en-python.md
  es/lecciones/normalizar-datos.md
  es/lecciones/palabras-clave-en-contexto-n-grams.md
  es/lecciones/poniendo-omeka-a-funcionar.md
  es/lecciones/preservar-datos-de-investigacion.md
  es/lecciones/reutilizacion-de-codigo-y-modularidad.md
  es/lecciones/salida-de-datos-como-archivo-html.md
  es/lecciones/salida-palabras-clave-contexto-ngrams.md
  es/lecciones/trabajar-con-archivos-de-texto.md
  es/lecciones/trabajar-con-paginas-web.md
  es/lecciones/transformacion-datos-xml-xsl.md
  es/lecciones/ver-archivos-html.md
  pt/licoes/preservar-os-seus-dados-de-investigacao.md
Labels: bug, technical

#2071 Removing travis
  .github/workflows/build.yml
  .travis.yml
Labels: technical

#2092 Publish french lesson: Calibrer des âges radiocarbone avec R
  _data/ph_authors.yml
  fr/consignes-traducteurs.md
  fr/lecons/analyse-corpus-antconc.md
  fr/lecons/calibration-radiocarbone-avec-r.md
  gallery/calibration-radiocarbone-avec-r.png
  gallery/originals/calibration-radiocarbone-avec-r-original.jpg
  images/calibration-radiocarbone-avec-r/calibration-1.png
  images/calibration-radiocarbone-avec-r/decroissance-1.png
  images/calibration-radiocarbone-avec-r/gauss-1.png
  images/calibration-radiocarbone-avec-r/hallstatt-1.png
  images/calibration-radiocarbone-avec-r/hpd-1.png
  images/calibration-radiocarbone-avec-r/intcal-1.png
  images/calibration-radiocarbone-avec-r/turin-cal-1.png
  images/calibration-radiocarbone-avec-r/turin-plot-1.png
  images/calibration-radiocarbone-avec-r/turin-uncal-1.png
Labels: french

#2091 Lesson request delete
  _data/snippets.yml
  _includes/menu.html
  en/lesson-requests.md
  es/solicitud-lecciones.md
  fr/appel-contributions.md
  fr/consignes-auteurs.md
  pt/licoes-pedidos.md
Labels: english, french, portuguese, spanish

#2096 New IPP (rstudio)
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: Communication, ProgHist Ltd

#2084 Update ph_authors.yml
  _data/ph_authors.yml
  _posts/2019-12-30-boletin-informativo.md
  _posts/2019-12-30-bulletin-de-information.md
  _posts/2019-12-30-newsletter.md
  _posts/2020-04-01-boletin-informativo-march20.md
  _posts/2020-04-01-bulletin-de-information-march20.md
  _posts/2020-04-01-newsletter-march20.md
  _posts/2020-07-01-boletin-informativo-junio20.md
  _posts/2020-07-01-bulletin-de-information-juin20.md
  _posts/2020-07-01-newsletter-june20.md
  _posts/2020-10-01-boletin-informativo-oct20.md
  _posts/2020-10-01-bulletin-de-information-oct20.md
  _posts/2020-10-01-newsletter-oct20.md
  avatars/ricardo-m-pimenta.png
Labels: Global Team, portuguese

#2099 Maj coquilles
  fr/consignes-redacteurs.md
Labels: enhancement
