Repository programminghistorian/jekyll, pull requests merged in 2021-07, with the labels that each got.

#2178 Publicar_introducao-ao-markdown
  pt/licoes/introducao-ao-markdown.md
Labels: portuguese, translation

#2170 Fix 2 typos in /en/author-guidelines
  en/author-guidelines.md
Labels: english

#2182 Publicar_camadas-vetoriais-qgis
  images/vector-layers-qgis/Figura11.jpg
  images/vector-layers-qgis/Figura12.jpg
  images/vector-layers-qgis/Figura17.jpg
  images/vector-layers-qgis/Figura18.jpg
  images/vector-layers-qgis/Figura19.jpg
  images/vector-layers-qgis/Figura20.jpg
  images/vector-layers-qgis/Figura3.jpg
  images/vector-layers-qgis/Figura5.jpg
  images/vector-layers-qgis/Figura6.jpg
  images/vector-layers-qgis/Figura7.jpg
  images/vector-layers-qgis/Figura8.jpg
  pt/licoes/camadas-vetoriais-qgis.md
Labels: portuguese, translation

#2184 Issue 2183 - remove new pub manager role
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: ProgHist Ltd

#2179 Create Doacoes.md New Portuguese Support-Us pages #2074
  _data/snippets.yml
  pt/apoiadores.md
  pt/apoie-nos.md
  pt/doacoes.md
  pt/ppi.md
Labels: portuguese

#2186 Actualizações e correcções nas páginas de directrizes autores, editores e tradutores
  pt/directrizes-autor.md
  pt/directrizes-editor.md
  pt/directrizes-tradutor.md
Labels: guidelines-update, portuguese

#2188 Publicar download-paginas-web-python
  _data/snippets.yml
  pt/licoes/download-paginas-web-python.md
Labels: portuguese, translation

#2166 Research update - AC / MJAL book chapter
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2190 Adding Anisa's profile and portrait to the site.
  _data/ph_authors.yml
  avatars/anisa-hawes.png
Labels: ProgHist Ltd

#2193 Editing team roles 'archivist'
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: ProgHist Ltd

#2194 Blog post anisa welcome
  _posts/2021-07-07-anisa-welcome.md
Labels: Communication, ProgHist Ltd

#2149 Update introduccion-map-warper.md
  es/lecciones/introduccion-map-warper.md
Labels: spanish

#2197 New patreron supporter
  en/supporters.md
  es/colaboradores.md
  es/lecciones/transformacion-datos-xml-xsl.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: ProgHist Ltd

#2128 Maintenance python lessons (round 1)
  en/lessons/applied-archival-downloading-with-wget.md
  en/lessons/downloading-multiple-records-using-query-strings.md
  en/lessons/from-html-to-list-of-words-2.md
  en/lessons/jupyter-notebooks.md
  en/lessons/output-data-as-html-file.md
  en/lessons/visualizing-with-bokeh.md
  en/lessons/working-with-text-files.md
  en/lessons/working-with-web-pages.md
  es/lecciones/de-html-a-lista-de-palabras-2.md
  es/lecciones/salida-de-datos-como-archivo-html.md
  es/lecciones/trabajar-con-archivos-de-texto.md
  es/lecciones/trabajar-con-paginas-web.md
  fr/lecons/travailler-avec-des-fichiers-texte.md
Labels: bug

#2202 Broken link in Leaflet lesson
  en/lessons/mapping-with-python-leaflet.md
Labels: bug

#2196 Mid year newsletter for 2021
  _posts/2021-07-12-newsletter.md
Labels: Communication

#2077 Guidelines update
  en/author-guidelines.md
  en/editor-guidelines.md
  en/lessons/crowdsourced-data-normalization-with-pandas.md
  en/research.md
  es/guia-editor.md
  es/guia-para-autores.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: guidelines-update

#2208 Publicar introducao omeka net
  images/up-and-running-with-omeka/intro-omeka-net-1.png
  images/up-and-running-with-omeka/intro-omeka-net-10.png
  images/up-and-running-with-omeka/intro-omeka-net-11.png
  images/up-and-running-with-omeka/intro-omeka-net-12.png
  images/up-and-running-with-omeka/intro-omeka-net-13.png
  images/up-and-running-with-omeka/intro-omeka-net-14.png
  images/up-and-running-with-omeka/intro-omeka-net-15.png
  images/up-and-running-with-omeka/intro-omeka-net-16.png
  images/up-and-running-with-omeka/intro-omeka-net-17.png
  images/up-and-running-with-omeka/intro-omeka-net-18.png
  images/up-and-running-with-omeka/intro-omeka-net-19.png
  images/up-and-running-with-omeka/intro-omeka-net-2.png
  images/up-and-running-with-omeka/intro-omeka-net-20.png
  images/up-and-running-with-omeka/intro-omeka-net-3.png
  images/up-and-running-with-omeka/intro-omeka-net-4.png
  images/up-and-running-with-omeka/intro-omeka-net-5.png
  images/up-and-running-with-omeka/intro-omeka-net-6.png
  images/up-and-running-with-omeka/intro-omeka-net-7.png
  images/up-and-running-with-omeka/intro-omeka-net-8.png
  images/up-and-running-with-omeka/intro-omeka-net-9.png
  pt/licoes/introducao-omeka-net.md
Labels: portuguese, translation

#2204 Update feedback.md
  en/feedback.md
  es/retroalimentacion.md
  fr/reaction.md
  pt/reportar-um-erro.md
Labels: ProgHist Ltd

#2212 New ES original lesson: "Introducción a TEI (parte 1)"
  _data/ph_authors.yml
  es/lecciones/introduccion-a-tei-1.md
  gallery/introduccion-a-tei-1.png
  gallery/originals/introduccion-a-tei-1-original.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-01.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-02.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-03.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-04.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-05.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-06.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-07.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-08.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-09.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-10.png
Labels: spanish

#2211 Updating author guidelines (FR and PT)
  fr/consignes-auteurs.md
  pt/directrizes-autor.md
Labels: guidelines-update
