Repository programminghistorian/jekyll, pull requests merged in 2021-06, with the labels that each got.

#2145 Link redirect fix - Contribute page
  en/contribute.md
Labels: bug

#2155 add Universidad de los Andes to IPP
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: Communication, ProgHist Ltd

#2151 Create Télécharger des pages web avec Python
  _posts/2016-05-10-PH-commitment-to-diversity.md
  en/research.md
  es/investigacion.md
  fr/lecons/telecharger-des-pages-web-avec-python.md
  fr/recherche.md
  pt/pesquisa.md
Labels: french, translation

#2121 Add publications and presentations of 1/2 2021 on 'research'
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2162 add 3x new IPPs
  en/lessons/creating-mobile-augmented-reality-experiences-in-unity.md
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: Communication, ProgHist Ltd

#2157 Remove the broken link and add some information to metadata #2150
  en/lessons/creating-an-omeka-exhibit.md
  en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  en/lessons/up-and-running-with-omeka.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
Labels: bug

#2163 Patreon new contributor june 2021
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: ProgHist Ltd

#2165 Actualizar directrizes-autor.md
  pt/directrizes-autor.md
Labels: portuguese, translation

#2169 fix broken links due to markdown errors
  en/translator-guidelines.md
Labels: english

#2172 Ucl support for accessibility report
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoie-nos.md
Labels: ProgHist Ltd

#2171 Blog Post - UCL Placement Stuents
  _posts/2021-06-26-ucl-placement-2021.md
Labels: Communication

#2176 New ES original lesson: "Animación y visualización de tablas históricas con R"
  _data/ph_authors.yml
  assets/visualizacion-y-animacion-de-tablas-historicas-con-R/atentados1959.xlsx
  es/lecciones/visualizacion-y-animacion-de-tablas-historicas-con-R.md
  gallery/originals/visualizacion-y-animacion-de-tablas-historicas-con-R.jpg
  gallery/visualizacion-y-animacion-de-tablas-historicas-con-R.png
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R1.jpg
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R2.png
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R3.png
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R4.png
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R5.png
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R6.png
  images/visualizacion-y-animacion-de-tablas-historicas-con-R/visualizacion-y-animacion-de-tablas-historicas-con-R7.gif
Labels: spanish
