Repository programminghistorian/jekyll, pull requests merged in 2021-08, with the labels that each got.

#2140 Build now ignores blog posts per #2106
  .github/workflows/build.yml
  _build/build.sh
  en/lessons/intro-to-twitterbots.md
  en/research.md
  es/investigacion.md
  fr/lecons/intro-aux-bots-twitter.md
  fr/recherche.md
  pt/pesquisa.md
Labels: technical

#2219 Adding PT project in EN, ES, FR about pages - Issue 2217
  en/about.md
  es/acerca-de.md
  fr/apropos.md
Labels: spanish, translation, french, english

#2224 Update ph_authors.yml
  _data/ph_authors.yml
Labels: french

#2229 Adding tiago project team
  _data/ph_authors.yml
  _posts/2021-07-12-newsletter.md
  avatars/tiago-sousa-garcia.png
Labels: ProgHist Ltd, 2021/22-JiscTNA

#2231 Issue #2230
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: ProgHist Ltd

#2233 remove brandon from team
  _data/ph_authors.yml
Labels: english

#2242 Added information and avatar for Nicolas Vaughan
  _data/ph_authors.yml
  avatars/nicolas-vaughan.png
Labels: spanish

#2245 update Crymble / Fernandez entries
  _data/ph_authors.yml
Labels: english

#2248 Add new IPP member to /supporters - Cambridge
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: ProgHist Ltd
