Repository programminghistorian/jekyll, pull requests merged in 2021-11, with the labels that each got.

#2348 Update r-basics-with-tabular-data.md
  en/lessons/r-basics-with-tabular-data.md
Labels: Lesson Maintenance

#2352 Issue 2351
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: ProgHist Ltd

#2114 Update consignes-auteurs.md
  assets/clustering-with-scikit-learn-in-python/data/DNP_ancient_authors.csv
  assets/clustering-with-scikit-learn-in-python/data/RELIGION_abstracts.csv
  assets/crowdsourced-data-normalization-with-pandas/Menu.csv
  fr/consignes-auteurs.md
  fr/modele-tuto.md
  pt/licoes/camadas-vetoriais-qgis.md
  pt/licoes/criar-exposicao-omeka.md
  pt/licoes/download-paginas-web-python.md
  pt/licoes/instalacao-linux.md
  pt/licoes/instalacao-mac.md
  pt/licoes/instalacao-windows.md
  pt/licoes/introducao-ao-markdown.md
  pt/licoes/introducao-instalacao-python.md
  pt/licoes/introducao-omeka-net.md
  pt/licoes/nocoes-basicas-R-dados-tabulares.md
  pt/licoes/nocoes-basicas-paginas-web-html.md
  pt/licoes/processamento-basico-texto-r.md
  pt/licoes/reutilizacao-codigo-modularidade-python.md
  pt/licoes/trabalhando-ficheiros-texto-python.md
Labels: enhancement, french, guidelines-update

#2350 Update ph_authors.yml
  _data/ph_authors.yml
Labels: french

#2345 Rm obsolete mention of notebooks using Python 2
  en/lessons/introduction-to-stylometry-with-python.md
  fr/lecons/introduction-a-la-stylometrie-avec-python.md
Labels: Lesson Maintenance, french, english

#2357 Update georeferencing-qgis.md
  en/lessons/georeferencing-qgis.md
Labels: Lesson Maintenance, english, portuguese

#2361 Update introduccion-a-tei-1.md
  en/lessons/correspondence-analysis-in-R.md
  es/lecciones/introduccion-a-tei-1.md
Labels: spanish

#2363 Proposal for Code of Conduct file
  CODE_OF_CONDUCT.md
Labels: enhancement

#2374 Issue 2373
  _data/ph_authors.yml
  _posts/2021-09-24-september-newsletter.md
Labels: Communication, ProgHist Ltd

#2367 Fix typo: missing word
  en/lessons/analyzing-documents-with-tfidf.md
Labels: Lesson Maintenance

#2368 Fix typo: tessaract -> tesseract
  en/lessons/OCR-and-Machine-Translation.md
Labels: Lesson Maintenance

#2358 Issue 2301
  en/lessons/mapping-with-python-leaflet.md
Labels: Lesson Maintenance, english

#2354 Rm warning - The Old Bailey API now works
  en/lessons/naive-bayesian.md
Labels: Lesson Maintenance, english

#2369 Issue 2343
  en/lessons/mac-installation.md
  es/lecciones/instalacion-mac.md
  images/mac-installation/BBEdit-hello-world.png
  images/mac-installation/BBEdit-hola-mundo.png
  images/mac-installation/BBEdit-ola-mundo.png
  images/mac-installation/TextWrangler-hello-world.png
  images/mac-installation/hello-world-terminal.png
  images/mac-installation/hola-mundo-terminal.png
  images/mac-installation/komodo-edit-mac.png
  images/mac-installation/ola-mundo-terminal.png
  pt/licoes/instalacao-mac.md
Labels: Lesson Maintenance, spanish, english, portuguese

#2286 Pt author guidelines review
  pt/directrizes-autor.md
Labels: enhancement, portuguese, guidelines-update

#2378 Issue 2377
  en/lessons/detecting-text-reuse-with-passim.md
  fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.md
Labels: Lesson Maintenance, french, english

#2365 Update introduccion-map-warper.md
  es/lecciones/introduccion-map-warper.md
Labels: Lesson Maintenance, spanish

#2376 Add Göttingen to IPP list
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2383 Publicar Manipular Strings com Python
  pt/licoes/manipular-strings-python.md
Labels: translation, portuguese

#2382 Issue 2381
  en/ipp.md
  es/pia.md
  fr/pi.md
  pt/ppi.md
Labels: Communication, ProgHist Ltd

#2392 Add info-alert to beginners-guide-to-twitter-data.md
  en/lessons/beginners-guide-to-twitter-data.md
Labels: Lesson Maintenance, english

#2395 Actualización lección TEI (parte 1)
  es/lecciones/introduccion-a-tei-1.md
  es/lecciones/introduccion-a-tei-2.md
Labels: spanish

#2375 adding new blog post about PH/JISC/TNA papers
  _posts/2021-11-15-articles-selected-ph-jisc-tna.md
Labels: Communication, ProgHist Ltd, 2021/22-JiscTNA

#2398 Publier generer jeu donnees texte ocr
  _data/ph_authors.yml
  assets/chiffres_romains_arabes.txt
  fr/lecons/generer-jeu-donnees-texte-ocr.md
Labels: translation, french

#2401 Issue 2400
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: spanish, french, english, Communication, portuguese

#2379 Issue 2366
  CODE_OF_CONDUCT.md
Labels: enhancement

#2387 Issue 2384
  assets/python-es-lecciones1.zip
  assets/python-es-lecciones2.zip
  assets/python-es-lecciones3.zip
  assets/python-es-lecciones4.zip
  assets/python-es-lecciones5.zip
  assets/python-es-lecciones6.zip
  assets/python-es-lecciones7.zip
  assets/python-es-lecciones8.zip
  assets/python-es-lecciones9.zip
  assets/python-lessons1.zip
  assets/python-lessons2.zip
  assets/python-lessons3.zip
  assets/python-lessons4.zip
  assets/python-lessons5.zip
  assets/python-lessons6.zip
  assets/python-lessons7.zip
  assets/python-lessons8.zip
  assets/python-lessons9.zip
  en/lessons/counting-frequencies.md
  en/lessons/downloading-multiple-records-using-query-strings.md
  en/lessons/from-html-to-list-of-words-1.md
  en/lessons/from-html-to-list-of-words-2.md
  en/lessons/normalizing-data.md
  en/lessons/output-data-as-html-file.md
  en/lessons/working-with-web-pages.md
  es/lecciones/contar-frecuencias.md
  es/lecciones/de-html-a-lista-de-palabras-1.md
  es/lecciones/de-html-a-lista-de-palabras-2.md
  es/lecciones/normalizar-datos.md
  es/lecciones/salida-de-datos-como-archivo-html.md
  es/lecciones/trabajar-con-paginas-web.md
  fr/lecons/telecharger-des-pages-web-avec-python.md
  pt/licoes/download-paginas-web-python.md
Labels: Lesson Maintenance, spanish, french, english, portuguese

#2406 Adding Gold Tier IPP membership option to en/ipp, es/pia, fr/pi, pt/ppi
  en/ipp.md
  es/pia.md
  fr/pi.md
  pt/ppi.md
Labels: Communication, ProgHist Ltd

#2408 Issue 2407
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2394 Update author-guidelines / guia-para-autores / consignes-auteurs / directrizes-autor
  en/author-guidelines.md
  es/guia-para-autores.md
  fr/consignes-auteurs.md
  pt/directrizes-autor.md
Labels: spanish, french, english, portuguese, guidelines-update

#2397 Revise beginners-guide-to-twitter-data.
  en/lessons/beginners-guide-to-twitter-data.md
  images/beginners-guide-to-twitter-data/all-values-populated.png
  images/beginners-guide-to-twitter-data/dataset-selection.png
  images/beginners-guide-to-twitter-data/decrease-decimal.png
  images/beginners-guide-to-twitter-data/doc-now-download.png
  images/beginners-guide-to-twitter-data/downloads.png
  images/beginners-guide-to-twitter-data/exports.png
  images/beginners-guide-to-twitter-data/first-return-value.png
  images/beginners-guide-to-twitter-data/format-as-numbers.png
  images/beginners-guide-to-twitter-data/format-for-vlookup.png
  images/beginners-guide-to-twitter-data/last-values.png
  images/beginners-guide-to-twitter-data/lookup-value.png
  images/beginners-guide-to-twitter-data/parameters-1.png
  images/beginners-guide-to-twitter-data/parameters-3.png
  images/beginners-guide-to-twitter-data/paste-special.png
  images/beginners-guide-to-twitter-data/preprocess-edges.png
  images/beginners-guide-to-twitter-data/statistics.png
  images/beginners-guide-to-twitter-data/table-array.png
  images/beginners-guide-to-twitter-data/vlookup-final.png
  images/beginners-guide-to-twitter-data/vlookup-formula-builder.png
  images/beginners-guide-to-twitter-data/vlookup-search.png
  images/beginners-guide-to-twitter-data/widen-columns.png
Labels: Lesson Maintenance, english
