Repository programminghistorian/jekyll, pull requests merged in 2021-09, with the labels that each got.

#2252 New original ES lesson: "Reutilizar colecciones digitales: GLAM Labs"
  _data/ph_authors.yml
  en/lessons/intro-to-linked-data.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
  es/lecciones/reutilizando-colecciones-digitales-glam-labs.md
  gallery/originals/reutilizando-colecciones-digitales-glam-labs-original.png
  gallery/reutilizando-colecciones-digitales-glam-labs.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs1.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs10.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs11.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs12.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs2.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs3.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs4.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs5.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs6.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs7.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs8.png
  images/reutilizando-colecciones-digitales-glam-labs/reutilizando-colecciones-digitales-glam-labs9.png
Labels: spanish

#2254 Issue #2167
  en/lessons/topic-modeling-and-mallet.md
  images/topic-modeling-and-mallet/fig1-advanced-system-settings.png
Labels: Lesson Maintenance

#2251 Add file with announcement of new 3 editors in ES Closes #2240
  _posts/2021-09-02-llano-gribomont-vaughan.md
  avatars/nicolas-llano.png
  en/lessons/geospatial-data-analysis.md
Labels: Communication

#2260 arregla diagramación lección glam labs
  es/lecciones/reutilizando-colecciones-digitales-glam-labs.md
Labels: spanish

#2262 Closes#2249 jisc tna ph cfp
  _posts/2021-09-08-cfp-jisc-ph.md
  images/jisc-na-ph-banner.png
Labels: Communication, 2021/22-JiscTNA

#2261 Update intro-to-linked-data.md
  en/lessons/intro-to-linked-data.md
Labels: english

#2265 Update ph_authors.yml and teamroles.yml
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: ProgHist Ltd

#2270 Update CFP blog post with link to booking page
  _posts/2021-09-08-cfp-jisc-ph.md
Labels: Communication, 2021/22-JiscTNA

#2272 Issue-2239
  _data/ph_authors.yml
Labels: spanish

#2263 Update french bio for Passim tuto
  _data/ph_authors.yml
Labels: translation, french

#2273 Issue 2200
  pt/licoes/instalacao-linux.md
  pt/licoes/instalacao-mac.md
  pt/licoes/instalacao-windows.md
Labels: portuguese

#2267 #2050
  en/lessons/intro-to-bash.md
  es/lecciones/introduccion-a-bash.md
Labels: Lesson Maintenance, spanish, english

#2268 Issue 1955 and 2028
  en/lessons/building-static-sites-with-jekyll-github-pages.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
Labels: Lesson Maintenance, spanish, english

#2275 Rename 2021-04-01-newsletter.md to 2021-04-01-newsletter-april-21.md
  _posts/2021-04-01-newsletter-april-21.md
  _posts/2021-07-12-mid-year-21-newsletter.md
Labels: Communication

#2271 Issue 2269
  en/lessons/detecting-text-reuse-with-passim.md
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: spanish, french, english, portuguese

#2278 Update instalacion-mac
  es/lecciones/instalacion-mac.md
Labels: Lesson Maintenance, spanish

#2279 Issue 1662
  en/lessons/visualizing-with-bokeh.md
Labels: Lesson Maintenance, english

#2281 Issue 2280
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: ProgHist Ltd

#2283 Issue 2282
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: ProgHist Ltd

#2285 Create Détecter la reutilisation de texte avec passim
  fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.md
Labels: translation, french

#2284 Publicar criar exposicao omeka
  images/creating-an-omeka-exhibit/criarexpo1.png
  images/creating-an-omeka-exhibit/criarexpo2.png
  images/creating-an-omeka-exhibit/criarexpo3.png
  pt/licoes/criar-exposicao-omeka.md
Labels: translation, portuguese

#2288 update lesson: "introducción a tei 1"
  es/lecciones/introduccion-a-tei-1.md
Labels: spanish

#2292 Changes related to becoming a charity in England and Wales
  _data/snippets.yml
  en/about.md
  en/ipp.md
  en/lessons/working-with-batches-of-pdf-files.md
  es/acerca-de.md
  es/pia.md
Labels: ProgHist Ltd

#2295 Added FAQs to JISC/TNA/PH CfP
  _posts/2021-09-08-cfp-jisc-ph.md
Labels: 2021/22-JiscTNA

#2299 Create 2021-09-24-september-newsletter.md
  _data/ph_authors.yml
  _posts/2021-09-24-september-newsletter.md
Labels: Communication

#2300 Update "becoming a charity" in PT
  _data/snippets.yml
  pt/ppi.md
  pt/sobre.md
Labels: translation, ProgHist Ltd, portuguese

#2291 deletes matchmaker text and link in Détecter la réutilisation de texte avec Passim
  en/lessons/detecting-text-reuse-with-passim.md
  fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.md
Labels: french

#2247 Project Team update - Remove Pimenta
  _data/ph_authors.yml
Labels: ProgHist Ltd, portuguese

#2305 Update changes becoming charity fr
  _data/snippets.yml
  fr/apropos.md
  fr/pi.md
Labels: translation, french, ProgHist Ltd

#2293 Create 2021-09-22-call-for-editors-en.md
  _posts/2021-09-22-call-for-editors-en.md
Labels: english, Communication

#2304 Retiring Intro to Beautiful Soup lesson
  en/lessons/retired/intro-to-beautiful-soup.md
Labels: french, english

#2303 Update authors info and avatar for Eric Brasil
  _data/ph_authors.yml
  avatars/eric-brasil.png
Labels: Global Team, portuguese

#2309 cambio 'significado semántico', que es redundante, por 'significado d…
  es/guia-para-autores.md
  es/guia-para-traductores.md
Labels: spanish

#2310 Publishing Clustering with Scikit
  _data/ph_authors.yml
  assets/clustering-with-scikit-learn-in-python/PH_Clustering_Tutorial_v2.ipynb
  assets/clustering-with-scikit-learn-in-python/data/DNP_ancient_authors.csv
  assets/clustering-with-scikit-learn-in-python/data/RELIGION_abstracts.csv
  en/lessons/clustering-with-scikit-learn-in-python.md
  gallery/clustering-with-scikit-learn-in-python.png
  gallery/originals/clustering-with-scikit-learn-in-python.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig1.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig10.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig11.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig12.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig2.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig3.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig4.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig5.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig6.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig7.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig8.png
  images/clustering-with-scikit-learn-in-python/clustering-with-sklearn-in-python-fig9.png
Labels: english

#2307 Light edit to jisc/tna cfp blog
  _posts/2021-09-08-cfp-jisc-ph.md
Labels: Communication, 2021/22-JiscTNA

#2313 Issue 2296
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2311 Update clustering-with-scikit-learn-in-python.md
  en/lessons/clustering-with-scikit-learn-in-python.md
Labels: english
