Repository programminghistorian/jekyll, pull requests merged in 2021-05, with the labels that each got.

#2116 Update ph_authors.yml
  _data/ph_authors.yml
  avatars/celian-ringwald.png
Labels: french

#2113 Issue 2110: update internal links in french lessons
  fr/lecons/debuter-avec-markdown.md
  fr/lecons/introduction-a-la-stylometrie-avec-python.md
  fr/lecons/travailler-avec-des-fichiers-texte.md
Labels: enhancement, french, translation

#2122 Change of business address
  en/individual.md
  es/donaciones.md
  fr/dons.md
  pt/apoie-nos.md
Labels: ProgHist Ltd

#2125 Publicar_nocoes-basicas-paginas-web-html
  .github/workflows/build.yml
  _build/build.sh
  _data/snippets.yml
  _layouts/lesson.html
  es/lecciones/administracion-de-datos-en-r.md
  pt/licoes/nocoes-basicas-paginas-web-html.md
Labels: portuguese, translation

#1994 Issue 1938
  .github/workflows/build.yml
  _build/build.sh
  _data/snippets.yml
  _layouts/lesson.html
Labels: technical

#2124 Add alt attributes
  _data/snippets.yml
  _includes/contact-info.html
  _includes/lesson_describe.html
  en/index.md
  pt/licoes/preservar-os-seus-dados-de-investigacao.md
Labels: bug, enhancement

#2129 Accessibility audit pt 2
  _includes/author-info.html
  _includes/homepage_block.html
  _includes/lesson_describe.html
  _includes/menu.html
  _layouts/lesson.html
  css/style.css
  js/header_links.js
Labels: bug, technical

#2133 Publicar_instalacao-linux
  pt/licoes/instalacao-linux.md
Labels: portuguese, translation

#2132 Publicar_instalacao-windows
  pt/licoes/instalacao-windows.md
Labels: portuguese, translation

#2131 Publicar_instalacao-mac
  pt/licoes/instalacao-mac.md
Labels: portuguese, translation

#2134 Publicar_introducao-instalacao-python
  pt/licoes/introducao-instalacao-python.md
Labels: portuguese, translation

#2137 Detecting reuse with passim
  _data/ph_authors.yml
  en/lessons/detecting-text-reuse-with-passim.md
  gallery/detecting-text-reuse-with-passim.png
  images/detecting-text-reuse-with-passim/plot-bible.png
  images/detecting-text-reuse-with-passim/plot-impresso.png
  images/detecting-text-reuse-with-passim/spark-dashboard.png
  images/detecting-text-reuse-with-passim/textreuse-generic.png
Labels: english

#2138 Publishing Crowdsourced Data Normalization with Pandas
  _data/ph_authors.yml
  assets/crowdsourced-data-normalization-with-pandas/Crowdsourced-Data-with-Pandas.ipynb
  assets/crowdsourced-data-normalization-with-pandas/Menu.csv
  en/lessons/crowdsourced-data-normalization-with-pandas.md
  gallery/crowdsourced-data-normalization-with-pandas.png
Labels: english

#2136 Add remaining alt text
  _data/snippets.yml
  en/author-guidelines.md
  en/contribute.md
  en/feedback.md
  en/individual.md
  en/ipp.md
  en/reviewer-guidelines.md
  en/translator-guidelines.md
  es/contribuciones.md
  es/guia-para-autores.md
  es/guia-para-revisores.md
  es/guia-para-traductores.md
  es/retroalimentacion.md
  fr/consignes-auteurs.md
  fr/consignes-evaluateurs.md
  fr/consignes-traducteurs.md
  fr/contribuer.md
  fr/reaction.md
  pt/contribua.md
  pt/directrizes-autor.md
  pt/directrizes-revisor.md
  pt/directrizes-tradutor.md
  pt/reportar-um-erro.md
Labels: bug, french, portuguese, spanish, technical, translation

#2135 Contrast fixes
  _includes/contact-info.html
  _includes/lesson_describe.html
  _layouts/lesson.html
  css/style.css
  js/header_links.js
Labels: bug, enhancement, technical

#1949 Sequence in Python lessons
  es/lecciones/contar-frecuencias.md
  es/lecciones/crear-y-ver-archivos-html-con-python.md
  es/lecciones/de-html-a-lista-de-palabras-1.md
  es/lecciones/de-html-a-lista-de-palabras-2.md
  es/lecciones/introduccion-e-instalacion.md
  es/lecciones/manipular-cadenas-de-caracteres-en-python.md
  es/lecciones/normalizar-datos.md
  es/lecciones/palabras-clave-en-contexto-n-grams.md
  es/lecciones/reutilizacion-de-codigo-y-modularidad.md
  es/lecciones/salida-de-datos-como-archivo-html.md
  es/lecciones/salida-palabras-clave-contexto-ngrams.md
  es/lecciones/trabajar-con-archivos-de-texto.md
  es/lecciones/trabajar-con-paginas-web.md
  es/lecciones/ver-archivos-html.md
Labels: Communication, spanish, technical
