Repository programminghistorian/jekyll, pull requests merged in 2021-02, with the labels that each got.

#1997 Fix bug on 'Creating and Viewing HTML files with Python'
  assets/python-es-lecciones5.zip
  assets/python-es-lecciones6.zip
  assets/python-lessons5.zip
  assets/python-lessons6.zip
  en/lessons/cleaning-ocrd-text-with-regular-expressions.md
  en/lessons/creating-and-viewing-html-files-with-python.md
  es/lecciones/crear-y-ver-archivos-html-con-python.md
Labels: bug, english, spanish

#2021 GitHub actions test
  .github/workflows/build.yml
  _posts/2019-09-26-welcome-martin-grandjean.md
  en/lessons/common-similarity-measures.md
  en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file.md
  en/lessons/retired/getting-started-with-github-desktop.md
  es/lecciones/introduccion-a-imageplot-y-la-visualizacion-de-metadatos.md
  es/lecciones/introduccion-map-warper.md
  es/lecciones/retirada/introduccion-control-versiones-github-desktop.md
Labels: technical

#2026 Testing breaking the site and status checks (along with adding status badges to our readme)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  README.md
Labels: technical

#2027 updated pull request template to remove references to travis
  .github/PULL_REQUEST_TEMPLATE.md
Labels: technical

#2015 Create file formulario.proposta.licao Issue 2014
  _posts/2019-09-26-welcome-martin-grandjean.md
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/Formulario.Consulta.Leccion.txt
  assets/forms/Lesson.Query.Form.txt
  assets/forms/formulario.proposta.licao.txt
  es/lecciones/retirada/introduccion-control-versiones-github-desktop.md
  pt/directrizes-autor.md
Labels: english, french, portuguese, spanish

#2033 Issue #2022
  avatars/Jimmy-medeiros.png
Labels: Global Team, portuguese

#2034 Delete Jimmy-medeiros.png
  avatars/Jimmy-medeiros.png
Labels: portuguese

#2032 Update ph_authors.yml
  _data/ph_authors.yml
  avatars/jimmy-medeiros.png
Labels: portuguese

#2029 New patrons added
  en/supporters.md
  es/colaboradores.md
  fr/nous-soutenir.md
  pt/apoie-nos.md
Labels: ProgHist Ltd

#2040 Issue 2039
  _data/snippets.yml
  pt/directrizes-editor.md
  pt/directrizes-revisor.md
  pt/directrizes-tradutor.md
Labels: portuguese, translation

#2038 Translation licoes-modelo.md
  pt/licoes-modelo.md
Labels: portuguese, translation

#2044 PH author profile creation #2043
  _data/ph_authors.yml
  avatars/matthias-gille-levenson.png
Labels: french

#2046 Issue 1930
  en/research.md
  research.md
Labels: Global Team, portuguese

#2051 Ph author profile creation 2045
  _data/ph_authors.yml
  avatars/gwenaelle-patat.png
Labels: french

#2052 Add new Educator tier Patron
  en/supporters.md
  es/colaboradores.md
Labels: Communication
