Repository programminghistorian/jekyll, pull requests merged in 2022-12, with the labels that each got.

#2770 Update download-multiplos-registros-query-strings.md
  pt/licoes/download-multiplos-registros-query-strings.md
Labels: portuguese

#2685 Issue 2536
  assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf
  assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf
  fr/consignes-auteurs.md
  pt/directrizes-autor.md
Labels: french, ProgHist Ltd, portuguese

#2749 Issue 2748
  _data/snippets.yml
  _includes/menu.html
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
  pt/vagas.md
Labels: Communication, ProgHist Ltd, Events

#2768 Update ph_authors.yml
  _data/ph_authors.yml
Labels: french, ProgHist Ltd

#2774 Issue 2773
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication

#2776 Update colaboradores.md
  es/colaboradores.md
Labels: Communication

#2781 add orcid to J Isasi per #2780
  _data/ph_authors.yml
Labels: enhancement

#2782 #2747 Adding the Jan event to the website
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: Communication

#2786 Issue 2785
  en/author-guidelines.md
  en/lessons/jupyter-notebooks.md
  en/translator-guidelines.md
  es/guia-para-autores.md
  es/guia-para-traductores.md
  fr/consignes-auteurs.md
  fr/consignes-redacteurs.md
  fr/consignes-traducteurs.md
  fr/lecons/introduction-aux-carnets-jupyter-notebooks.md
  pt/directrizes-autor.md
  pt/directrizes-tradutor.md
Labels: Lesson Maintenance, french, english

#2788 Update ph_authors.yml
  _data/ph_authors.yml
  _data/snippets.yml
Labels: french, ProgHist Ltd

#2790 Issue2789
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: french, ProgHist Ltd

#2766 Publicar Autoria Sustentável em Texto Simples usando Pandoc e Markdown
  assets/teste.md
  images/sustainable-authorship-in-plain-text-using-pandoc-and-markdown/autoria-sustentavel-texto-simples-pandoc-markdown-01.png
  pt/licoes/autoria-sustentavel-texto-simples-pandoc-markdown.md
Labels: translation, portuguese

#2791 Issue2709
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: Communication

#2755 Issue 2753
  en/lessons/sonification.md
  pt/licoes/som-dados-sonificacao-historiadores.md
Labels: Lesson Maintenance, english, portuguese

#2799 Issue 2797 2798
  en/lessons/OCR-and-Machine-Translation.md
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Lesson Maintenance, english, ProgHist Ltd

#2801 Issue 2800
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/Formulario.Consulta.Leccion.txt
  assets/forms/Lesson.Query.Form.txt
  assets/forms/formulario.proposta.licao.txt
Labels: french, ProgHist Ltd

#2792 #2784 insertion of blog post
  _posts/2022-12-16-2022-in-review.md
  images/blog/Review-2022-Picture2.png
Labels: Communication

#2804 Issue 2802
  en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file.md
  fr/lecons/generer-jeu-donnees-texte-ocr.md
Labels: Lesson Maintenance, french, english
