Repository programminghistorian/jekyll, pull requests merged in 2022-10, with the labels that each got.

#2697 Issue 2696
  en/lessons/building-static-sites-with-jekyll-github-pages.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
Labels: Lesson Maintenance, spanish, english

#2693 Issue 2689
  assets/text-mining-with-extracted-features/extracted-features-lesson_files.zip
  assets/text-mining-with-extracted-features/sample.md
  en/lessons/text-mining-with-extracted-features.md
Labels: Lesson Maintenance, english

#2690 Issue 2671 - adding to the research / investigacion / recherche / pesquisa pages
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2698 Update teamroles.yml
  _data/teamroles.yml
Labels: technical, ProgHist Ltd

#2704 publishing scalable reading of structured data
  _data/ph_authors.yml
  en/lessons/scalable-reading-of-structured-data.md
  gallery/originals/scalable-reading-of-structured-data-original.png
  gallery/scalable-reading-of-structured-data.png
  images/scalable-reading-of-structured-data/scalable-reading-of-structured-data-1.png
  images/scalable-reading-of-structured-data/scalable-reading-of-structured-data-2.png
  images/scalable-reading-of-structured-data/scalable-reading-of-structured-data-3.png
Labels: english

#2705 Fix nav redirects
  es/colaboradores.md
  es/donaciones.md
  es/guia-para-autores.md
  es/guia-para-traductores.md
  es/jisc-tna-colaboracion.md
  es/pia.md
  fr/dons.md
  fr/jisc-tna-partenariat.md
  fr/nos-soutiens.md
  fr/pi.md
  pt/apoiadores.md
  pt/doacoes.md
  pt/jisc-tna-parceria.md
  pt/ppi.md
Labels: technical

#2716 Issue 2710
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: ProgHist Ltd

#2715 Update ph_authors.yml
  _data/ph_authors.yml
Labels: french, ProgHist Ltd

#2718 Publicar lição "De HTML para Lista de Palavras (parte 1)"
  pt/licoes/HTML-lista-palavras-1.md
Labels: translation, portuguese

#2719 Publicar lição "De HTML para Lista de Palavras (parte 2)"
  pt/licoes/HTML-lista-palavras-2.md
Labels: translation, portuguese

#2720 Publicar "Normalização de Dados Textuais com Python"
  pt/licoes/normalizacao-dados-textuais-python.md
Labels: translation, portuguese

#2711 publishing map warper translation
  _data/ph_authors.yml
  en/lessons/introduction-map-warper.md
  images/introduccion-map-warper/Draw_new_polygon.gif
  images/introduccion-map-warper/Zoom_lock.png
  images/introduccion-map-warper/account.gif
  images/introduccion-map-warper/add_control_point.gif
  images/introduccion-map-warper/add_custom_basemap.png
  images/introduccion-map-warper/addcustombasemap.png
  images/introduccion-map-warper/csvicon.png
  images/introduccion-map-warper/mapwarper_controlpoints.png
  images/introduccion-map-warper/mapwarper_controlpoints_rmserrordelete.png
  images/introduccion-map-warper/mapwarper_controlpointsadded.png
  images/introduccion-map-warper/mapwarper_openstreetmap.png
  images/introduccion-map-warper/mapwarper_preview.png
  images/introduccion-map-warper/mapwarper_satellite.png
  images/introduccion-map-warper/mapwarper_showmap.png
  images/introduccion-map-warper/mapwarper_warpbutton.png
  images/introduccion-map-warper/mapwarper_warped.png
  images/introduccion-map-warper/move_around_map.gif
  images/introduccion-map-warper/move_control_point.gif
  images/introduccion-map-warper/rss.png
Labels: spanish, translation, english

#2722 Publicar "Criação e Visualização de Ficheiros HTML com Python"
  pt/licoes/criacao-visualizacao-ficheiros-html-python.md
Labels: translation, portuguese
