Repository programminghistorian/jekyll, pull requests merged in 2022-05, with the labels that each got.

#2569 Issue 2568
  en/lessons/building-static-sites-with-jekyll-github-pages.md
  es/lecciones/corpus-paralelo-lfaligner.md
  es/lecciones/introduccion-a-tei-1.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
Labels: Lesson Maintenance, spanish, english

#2576 Issue 2575
  en/lessons/intro-to-twitterbots.md
  fr/lecons/intro-aux-bots-twitter.md
Labels: Lesson Maintenance, french, english

#2573 Issue 2572
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2574 Update of bibliographical reference in the two TEI lessons (in PH Spanish).
  es/lecciones/introduccion-a-tei-1.md
  es/lecciones/introduccion-a-tei-2.md
Labels: spanish

#2567 Publish Displaying and Georeferencing Historical Maps
  _data/ph_authors.yml
  en/lessons/displaying-georeferenced-map-knightlab-storymap-js.md
  gallery/displaying-georeferenced-map-knightlab-storymap-js.png
  gallery/originals/displaying-georeferenced-map-knightlab-storymap-js-original.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_Cities_Slides.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_Default_Options.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_GoogleSignin.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_MakeMap.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_MapType_Custom.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_NC_ZoomedIn.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_Raleigh.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_TileLayer.png
  images/displaying-georeferenced-map-knightlab-storymap-js/StoryMapJS_Title_Create.png
  images/displaying-georeferenced-map-knightlab-storymap-js/addingcontent_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/addnewslide_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/ashevilleNCgeoreferencedmap_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/create_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/custommapmarkers_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/displayrouteline_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/gmail_signin.png
  images/displaying-georeferenced-map-knightlab-storymap-js/make_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/maptype_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/mapwarper_export.png
  images/displaying-georeferenced-map-knightlab-storymap-js/mapwarper_showmap.png
  images/displaying-georeferenced-map-knightlab-storymap-js/mapwarperurl_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/options_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/overviewauthoringtool_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/raleighNCgeoreferencedmap_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/tilelayer_storymapjs.png
  images/displaying-georeferenced-map-knightlab-storymap-js/treatasimage_storymapjs.png
Labels: english

#2579 Issue 2533
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication, ProgHist Ltd

#2584 Update gravity-model.md
  en/lessons/gravity-model.md
Labels: Lesson Maintenance, english

#2581 Issue 2580
  _posts/2022-04-28-education-and-community-lead.md
  images/blog/Job-Description-Education-and-Community-Lead.pdf
Labels: ProgHist Ltd

#2585 Issue 2582
  _data/snippets.yml
  _includes/menu.html
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: ProgHist Ltd

#2587 Issue 2586
  _data/ph_authors.yml
  _data/teamroles.yml
Labels: ProgHist Ltd

#2589 Issue 2588
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2591 Issue 2590
  _data/ph_authors.yml
Labels: Communication, ProgHist Ltd
