Repository programminghistorian/jekyll, pull requests merged in 2022-07, with the labels that each got.

#2618 Update ph_authors.yml
  _data/ph_authors.yml
Labels: Communication, ProgHist Ltd

#2620 Issue 2536
  assets/forms/Authorial-copyright-and-publishing-rights.pdf
  assets/forms/Derechos-de-autor-y-de-publicación.pdf
  en/author-guidelines.md
  es/guia-para-autores.md
Labels: spanish, policy, english, guidelines-update

#2615 Issue 2612
  _includes/figure.html
  en/lessons/interactive-text-games-using-twine.md
Labels: enhancement, technical

#2623 Issue 2622
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2634 trying to get htmlproofer working
  .github/workflows/build.yml
  Gemfile
  Gemfile.lock
  _build/build.sh
  _config.yml
  assets/forms/Derechos-de-autor-y-de-publicación.pdf
Labels: technical

#2628 Issue 2627
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2636 Issue2635
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2639 Issue 2638
  _data/ph_authors.yml
  avatars/gisele-almeida.png
Labels: ProgHist Ltd

#2641 Create 2022-07-28-gisele-welcome.md
  _posts/2022-07-28-gisele-welcome.md
  avatars/gisele-almeida.png
Labels: Communication, ProgHist Ltd

#2632 Issue 2631
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: french, ProgHist Ltd
