Repository programminghistorian/jekyll, pull requests merged in 2022-08, with the labels that each got.

#2646 Fix ES lesson DOI
  es/lecciones/descarga-multiples-registros-usando-cadenas-de-consulta.md
Labels: spanish

#2650 Issue 2649
  en/lessons/introduction-to-ffmpeg.md
  es/lecciones/introduccion-a-ffmpeg.md
Labels: Lesson Maintenance, spanish, english

#2648 Issue 2629
  en/lessons/basic-text-processing-in-r.md
  es/lecciones/procesamiento-basico-de-textos-en-r.md
  pt/licoes/processamento-basico-texto-r.md
Labels: Lesson Maintenance, spanish, english, portuguese

#2651 Update reutilizando-colecciones-digitales-glam-labs.md
  es/lecciones/reutilizando-colecciones-digitales-glam-labs.md
Labels: enhancement, spanish

#2645 Publicar Introdução à codificação de textos em TEI (parte 1)
  images/introduccion-a-tei-1/introducao-codificacao-texto-tei-1-01.png
  pt/licoes/introducao-codificacao-textos-tei-1.md
Labels: translation, portuguese

#2652 Update ph_authors.yml
  _data/ph_authors.yml
Labels: ProgHist Ltd

#2656 #2626 added recent research activities to add to research/investigacion/recherche/pesquisa
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2658 2657
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2664 new ES lesson: "Exhibición digital mínima e interactiva con CollectionBuilder"
  assets/exhibicion-con-collection-builder/collectionbuilder-metadata-template.csv
  en/lessons/installing-omeka.md
  es/lecciones/exhibicion-con-collection-builder.md
  gallery/exhibicion-con-collection-builder.png
  gallery/originals/exhibicion-con-collection-builder-original.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder01.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder02.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder03.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder04.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder05.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder06.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder07.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder08.png
  images/exhibicion-con-collection-builder/exhibicion-con-collection-builder09.png
Labels: spanish

#2666 change in the wording for lesson-difficulty in ES
  _data/snippets.yml
Labels: spanish, translation
