Repository programminghistorian/jekyll, pull requests merged in 2022-03, with the labels that each got.

#2504 Add table-wrapper to style CSS
  css/style.css
  en/lessons/mapping-with-python-leaflet.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
Labels: technical

#2509 Issue 2508
  en/lessons/introduction-to-stylometry-with-python.md
  fr/lecons/introduction-a-la-stylometrie-avec-python.md
Labels: Lesson Maintenance, french, english

#2507 Update download-paginas-web-python.md
  pt/licoes/download-paginas-web-python.md
Labels: Lesson Maintenance, portuguese

#2511 Issue 2502
  en/lessons/temporal-network-analysis-with-r.md
  es/lecciones/analisis-temporal-red.md
Labels: Lesson Maintenance, spanish, english

#2512 Fixing lesson testers
  _layouts/lesson.html
Labels: technical

#2513 Fix lesson tables
  css/style.css
  en/lesson-template.md
  es/plantilla-leccion.md
  fr/modele-tuto.md
  pt/licoes-modelo.md
Labels: technical

#2516 Publicar Instalação de Módulos Python com pip
  pt/licoes/instalacao-modulos-python-pip.md
Labels: translation, portuguese

#2518 Issue 2517
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2522 Issue 2521
  _data/ph_authors.yml
  en/feedback.md
  en/research.md
  es/investigacion.md
  es/retroalimentacion.md
  fr/reaction.md
  fr/recherche.md
  pt/pesquisa.md
  pt/reportar-um-erro.md
Labels: ProgHist Ltd

#2524 Issue 2523 topic r
  _data/topics.yml
  en/editor-guidelines.md
  en/lessons/basic-text-processing-in-r.md
  en/lessons/correspondence-analysis-in-R.md
  en/lessons/data_wrangling_and_management_in_R.md
  en/lessons/getting-started-with-mysql-using-r.md
  en/lessons/r-basics-with-tabular-data.md
  en/lessons/temporal-network-analysis-with-r.md
  es/guia-editor.md
  es/lecciones/administracion-de-datos-en-r.md
  es/lecciones/analisis-de-sentimientos-r.md
  es/lecciones/analisis-temporal-red.md
  es/lecciones/datos-tabulares-en-r.md
  es/lecciones/procesamiento-basico-de-textos-en-r.md
  es/lecciones/visualizacion-y-animacion-de-tablas-historicas-con-R.md
  fr/consignes-redacteurs.md
  fr/lecons/calibration-radiocarbone-avec-r.md
  pt/directrizes-editor.md
  pt/licoes/nocoes-basicas-R-dados-tabulares.md
  pt/licoes/processamento-basico-texto-r.md
Labels: enhancement, technical, Communication

#2519 Update Melton affiliation info
  _data/ph_authors.yml
  en/lessons/transforming-xml-with-xsl.md
  es/lecciones/transformacion-datos-xml-xsl.md
Labels: spanish, french, english, portuguese

#2526 Issue 2525
  _data/topics.yml
  en/about.md
  es/acerca-de.md
  fr/apropos.md
  pt/sobre.md
Labels: ProgHist Ltd

#2530 Issue 2529
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: ProgHist Ltd
