Repository programminghistorian/jekyll, pull requests merged in 2022-01, with the labels that each got.

#2457 Issue 2455
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2461 update Sofia affiliation and bio
  _data/ph_authors.yml
  _data/teamroles.yml
  en/lessons/sonification.md
Labels: french

#2459 Issue 2453
  en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
  fr/lecons/redaction-durable-avec-pandoc-et-markdown.md
Labels: Lesson Maintenance, spanish, french, english

#2464 Remove bad comment
  _includes/lesson_describe.html
Labels: enhancement, technical

#2467 Issue 2463
  gallery/detecting-text-reuse-with-passim.png
  gallery/gravity-model.png
  gallery/working-with-batches-of-pdf-files.png
Labels: technical, english
