Repository programminghistorian/jekyll, pull requests merged in 2022-06, with the labels that each got.

#2596 Issue 2595
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: Communication, ProgHist Ltd

#2599 Issue 2598
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2602 Update author-guidelines.md
  en/author-guidelines.md
Labels: technical

#2608 Update extracting-illustrated-pages.md
  en/lessons/extracting-illustrated-pages.md
Labels: Lesson Maintenance, english

#2609 Second try issue 2603
  en/lessons/basic-text-processing-in-r.md
  es/lecciones/procesamiento-basico-de-textos-en-r.md
  pt/licoes/processamento-basico-texto-r.md
Labels: Lesson Maintenance, spanish, english, portuguese

#2605 Publicar Introdução à estilometria com Python
  assets/introduction-to-stylometry-with-python/dataset_estilometria.zip
  images/introduction-to-stylometry-with-python/introducao-estilometria-python-01.jpeg
  pt/licoes/introducao-estilometria-python.md
Labels: translation, portuguese
