Repository programminghistorian/jekyll, pull requests merged in 2022-09, with the labels that each got.

#2669 fixes a small typo in "unsupervised learning"
  en/lessons/computer-vision-deep-learning-pt1.md
Labels: english

#2676 Update introduction-to-populating-a-website-with-api-data.md
  en/lessons/introduction-to-populating-a-website-with-api-data.md
Labels: Lesson Maintenance, english

#2674 Update ph_authors.yml
  _data/ph_authors.yml
Labels: french

#2681 Issue 2680
  _data/ph_authors.yml
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/Formulario.Consulta.Leccion.txt
  assets/forms/Lesson.Query.Form.txt
  assets/forms/formulario.proposta.licao.txt
  en/author-guidelines.md
  en/contribute.md
  es/contribuciones.md
  es/guia-para-autores.md
  fr/consignes-auteurs.md
  fr/contribuer.md
  pt/contribua.md
  pt/directrizes-autor.md
Labels: spanish, french, english, ProgHist Ltd, portuguese

#2616 Partnership banner logic
  _data/snippets.yml
  _layouts/lesson.html
  en/jisc-tna-partnership.md
  es/jisc-tna-colaboracion.md
  fr/jisc-tna-partenariat.md
  pt/jisc-tna-parceria.md
Labels: enhancement, technical, 2021/22-JiscTNA
