Repository programminghistorian/jekyll, pull requests merged in 2023-10, with the labels that each got.

#3032 Issue 3031
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#3034 Update clustering-visualizing-word-embeddings.md
  en/lessons/clustering-visualizing-word-embeddings.md
Labels: English

#3038 Issue 3037
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: English, Community

#3041 Update research pages
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Español, Français, English, ProgHist, Português, Research

#3043 Update analisis-voyant-tools.md
  es/lecciones/analisis-voyant-tools.md
Labels: Lesson Maintenance, Español

#3045 Issue 3044
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#3051 Upload corpus-analysis-with-spacy.ipynb
  assets/corpus-analysis-with-spacy/corpus-analysis-with-spacy.ipynb
Labels: English

#3047 Publicar Git como ferramenta metodológica em projetos de História (parte 1)
  gallery/git-ferramenta-metodologica-projetos-historia-1.png
  gallery/originals/git-ferramenta-metodologica-projetos-historia-1-original.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-01.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-02.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-03.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-04.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-05.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-06.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-07.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-08.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-09.png
  images/git-ferramenta-metodologica-projetos-historia-1/or-pt-git-ferramenta-metodologica-projetos-historia-1-10.png
  pt/licoes/git-ferramenta-metodologica-projetos-historia-1.md
Labels: Português

#3057 Issue 3056
  es/contribuciones.md
  es/guia-para-revisores.md
  es/lecciones/analisis-voyant-tools.md
  es/lecciones/corpus-paralelo-lfaligner.md
Labels: Lesson Maintenance, Español

#3059 Issue 3058
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist
