Repository programminghistorian/jekyll, pull requests merged in 2023-05, with the labels that each got.

#2936 Publicar sumarizacao narrativas web python
  _data/ph_authors.yml
  gallery/originals/sumarizacao-narrativas-web-python.png
  gallery/sumarizacao-narrativas-web-python.png
  images/sumarizacao-narrativas-web-python/sumarizacao-narrativas-web-python-1.jpeg
  images/sumarizacao-narrativas-web-python/sumarizacao-narrativas-web-python-2.jpeg
  images/sumarizacao-narrativas-web-python/sumarizacao-narrativas-web-python-3.jpeg
  images/sumarizacao-narrativas-web-python/sumarizacao-narrativas-web-python-4.jpeg
  pt/licoes/sumarizacao-narrativas-web-python.md
Labels: Português, 2021/22-JiscTNA

#2941 Issue 2940
  _data/ph_authors.yml
  _data/teamroles.yml
  _includes/project-team-loop.html
Labels: ProgHist

#2945 Update to Spanish lesson, 'Introducción a la codificación de textos e…
  assets/introduccion-a-tei-1/plantilla-TEI.xml
  es/lecciones/introduccion-a-tei-1.md
  images/introduccion-a-tei-1/introduccion-a-tei-1-01.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-02.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-03.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-04.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-05.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-06.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-07.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-08.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-09.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-10.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-11.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-12.png
  images/introduccion-a-tei-1/introduccion-a-tei-1-13.png
  researchpapers/Afanador_Paper_DH2018_The_Programming_Historian_en_Español.pdf
Labels: Lesson Maintenance, Español

#2939 Publicar extrair-paginas-ilustradas-com-python
  pt/licoes/extrair-paginas-ilustradas-com-python.md
Labels: Translation, Português

#2938 Publicar georreferenciamento-qgis
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-1.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-10.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-11.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-13.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-15.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-17.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-18.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-19.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-2.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-20.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-21.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-5.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-6.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-8.png
  images/georeferencing-qgis/tr-pt-georeferencing-qgis-9.png
  pt/licoes/georreferenciamento-qgis.md
Labels: Translation, Português

#2937 Publicar_limpar-dados-openrefine
  images/cleaning-data-with-openrefine/tr-pt-cleaning-data-with-openrefine-1.png
  images/cleaning-data-with-openrefine/tr-pt-cleaning-data-with-openrefine-2.png
  pt/licoes/limpar-dados-openrefine.md
Labels: Translation, Português

#2951 Update administracion-de-datos-en-r.md
  es/lecciones/administracion-de-datos-en-r.md
Labels: Lesson Maintenance, Español

#2949 Publicar analise-correspondencia-pesquisa-historica-R
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-1.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-2.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-3.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-4.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-5.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-6.1.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-6.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-7.png
  images/correspondence-analysis-in-R/tr-pt-analise-correspondenciaR-8.png
  pt/licoes/analise-correspondencia-pesquisa-historica-R.md
Labels: Translation, Português

#2955 Update topics.yml
  _data/topics.yml
Labels: Enhancement, Technical

#2953 Remove duplicate file from /researchpapers
  researchpapers/Afanador_Paper_DH2018_The_Programming_Historian_en_Español.pdf
Labels: Technical
