Repository programminghistorian/jekyll, pull requests merged in 2023-03, with the labels that each got.

#2872 Issue 2871
  en/lessons/jupyter-notebooks.md
  en/lessons/visualizing-with-bokeh.md
  es/lecciones/reutilizando-colecciones-digitales-glam-labs.md
  fr/lecons/introduction-aux-carnets-jupyter-notebooks.md
Labels: Lesson Maintenance, spanish, french, english

#2873 Issue 2866
  _data/snippets.yml
  _layouts/lesson.html
Labels: technical, ProgHist Ltd

#2881 create decomptes-de-frequences-de-mots-en-python.md
  fr/lecons/decomptes-de-frequences-de-mots-en-python.md
Labels: french

#2883 Issue 2874
  en/lessons/building-static-sites-with-jekyll-github-pages.md
  en/lessons/collaborative-blog-with-jekyll-github.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
Labels: Lesson Maintenance, spanish, english

#2882 Issue 2829
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2888 Update visualizing-with-bokeh.md
  en/lessons/visualizing-with-bokeh.md
Labels: Lesson Maintenance, english

#2870 Issue 2869
  _data/ph_authors.yml
  _data/teamroles.yml
  _includes/project-team-loop.html
  avatars/adam-crymble.png
  en/project-team.md
  es/equipo-de-proyecto.md
  fr/equipe-projet.md
  pt/equipe.md
Labels: ProgHist Ltd

#2889 Issue 2886
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: Communication, ProgHist Ltd, Events

#2885 Issue 2884
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Communication, ProgHist Ltd

#2900 Issue 2899
  _data/ph_authors.yml
  avatars/daphne-mathelier.png
Labels: french

#2904 Update analisis-de-corpus-con-antconc.md
  es/lecciones/analisis-de-corpus-con-antconc.md
Labels: Lesson Maintenance, spanish

#2907 Update applied-archival-downloading-with-wget.md
  en/lessons/applied-archival-downloading-with-wget.md
Labels: Lesson Maintenance, english

#2909 Update image-classification-neural-networks.md
  en/lessons/image-classification-neural-networks.md
Labels: english, 2021/22-JiscTNA
