Repository programminghistorian/jekyll, pull requests merged in 2023-02, with the labels that each got.

#2845 #2751
  en/events.md
  en/ipp.md
  es/eventos.md
  es/pia.md
  fr/manifestations.md
  fr/pi.md
  pt/eventos.md
  pt/ppi.md
Labels: Communication

#2847 Issue 2842
  en/lessons/analyzing-documents-with-tfidf.md
  fr/lecons/analyse-de-documents-avec-tfidf.md
Labels: Lesson Maintenance, french, english

#2846 Issue 2754
  en/lessons/computer-vision-deep-learning-pt1.md
  images/computer-vision-deep-learning-pt1/kaggle_gpu.png
Labels: Lesson Maintenance, english

#2850 Issue 2849
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: french, ProgHist Ltd

#2854 Update consignes-auteurs.md
  fr/consignes-auteurs.md
Labels: french, ProgHist Ltd

#2852 Publish transcription automatisee graphies non latines
  _data/ph_authors.yml
  fr/lecons/transcription-automatisee-graphies-non-latines.md
  gallery/originals/transcription-automatisee-graphies-non-latines-original.png
  gallery/transcription-automatisee-graphies-non-latines.png
  images/transcription-automatisee-graphies-non-latines/cursive/000005.gt.txt
  images/transcription-automatisee-graphies-non-latines/cursive/000005.png
  images/transcription-automatisee-graphies-non-latines/figure0_PG_125_1103-1104.jpg
  images/transcription-automatisee-graphies-non-latines/figure0_PG_125_625-626.jpg
  images/transcription-automatisee-graphies-non-latines/figure10_PG_123_202.jpg
  images/transcription-automatisee-graphies-non-latines/figure10_text.jpg
  images/transcription-automatisee-graphies-non-latines/figure11_PG-result.jpeg
  images/transcription-automatisee-graphies-non-latines/figure11_bbox_polygon.jpeg
  images/transcription-automatisee-graphies-non-latines/figure12_Precision_rappel.jpeg
  images/transcription-automatisee-graphies-non-latines/figure12_time_saved_transcription.png
  images/transcription-automatisee-graphies-non-latines/figure13_defaultLayout.jpeg
  images/transcription-automatisee-graphies-non-latines/figure14_Steps_CalfaVision_1.jpg
  images/transcription-automatisee-graphies-non-latines/figure15_Steps_CalfaVision_2.jpg
  images/transcription-automatisee-graphies-non-latines/figure16_projet.jpg
  images/transcription-automatisee-graphies-non-latines/figure17_layout2.jpg
  images/transcription-automatisee-graphies-non-latines/figure18_pred_PG.jpeg
  images/transcription-automatisee-graphies-non-latines/figure19_text.jpg
  images/transcription-automatisee-graphies-non-latines/figure1_composantes.png
  images/transcription-automatisee-graphies-non-latines/figure1_pipeline_training_1.jpg
  images/transcription-automatisee-graphies-non-latines/figure20_PG-result.jpeg
  images/transcription-automatisee-graphies-non-latines/figure21_time_saved_transcription.png
  images/transcription-automatisee-graphies-non-latines/figure2_composantes.jpg
  images/transcription-automatisee-graphies-non-latines/figure2_pipeline-htr.jpeg
  images/transcription-automatisee-graphies-non-latines/figure3_CER-layout.png
  images/transcription-automatisee-graphies-non-latines/figure3_pipeline-htr.jpeg
  images/transcription-automatisee-graphies-non-latines/figure4_PG_123_359-360.jpg
  images/transcription-automatisee-graphies-non-latines/figure4_PG_125_625-626.jpg
  images/transcription-automatisee-graphies-non-latines/figure5_exemples-PG.png
  images/transcription-automatisee-graphies-non-latines/figure5_pipeline_training_2.jpg
  images/transcription-automatisee-graphies-non-latines/figure6_PG_123_202.jpg
  images/transcription-automatisee-graphies-non-latines/figure6_pipeline_training_3.jpg
  images/transcription-automatisee-graphies-non-latines/figure7_CER-layout.jpg
  images/transcription-automatisee-graphies-non-latines/figure7_CER-layout.png
  images/transcription-automatisee-graphies-non-latines/figure7_defaultLayout.jpeg
  images/transcription-automatisee-graphies-non-latines/figure8_PG_123_359-360.jpg
  images/transcription-automatisee-graphies-non-latines/figure8_PG_125_625-626.jpg
  images/transcription-automatisee-graphies-non-latines/figure8_projet.jpg
  images/transcription-automatisee-graphies-non-latines/figure9_exemples-PG.png
  images/transcription-automatisee-graphies-non-latines/figure9_layout2.jpg
  images/transcription-automatisee-graphies-non-latines/gaza/000014.gt.txt
  images/transcription-automatisee-graphies-non-latines/gaza/000014.png
  images/transcription-automatisee-graphies-non-latines/gtcommantaries/cu31924087948174_0063_70.png
  images/transcription-automatisee-graphies-non-latines/precision_rappel/BULAC_MS_ARA_1947_178658_GT.jpg
  images/transcription-automatisee-graphies-non-latines/precision_rappel/BULAC_MS_ARA_1947_178658_P-bas_R-bas.jpg
  images/transcription-automatisee-graphies-non-latines/precision_rappel/BULAC_MS_ARA_1947_178658_P-bas_R-haut.jpg
  images/transcription-automatisee-graphies-non-latines/precision_rappel/BULAC_MS_ARA_1947_178658_P-haut_R-bas.jpg
  images/transcription-automatisee-graphies-non-latines/sample.md
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image1.png
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image2.png
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image3.png
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image4.png
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image5.png
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image6.png
  images/transcription-automatisee-graphies-non-latines/tableau_alpha/image7.png
  images/transcription-automatisee-graphies-non-latines/voulgaris/000007.gt.txt
  images/transcription-automatisee-graphies-non-latines/voulgaris/000007.png
Labels: french

#2856 Update transcription-automatisee-graphies-non-latines.md
  fr/lecons/transcription-automatisee-graphies-non-latines.md
Labels: french, ProgHist Ltd, 2021/22-JiscTNA

#2858 #2816
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: Communication

#2851 Issue 2483
  en/lessons/introduction-to-stylometry-with-python.md
  fr/lecons/introduction-a-la-stylometrie-avec-python.md
  pt/licoes/introducao-estilometria-python.md
Labels: Lesson Maintenance, french, english, portuguese

#2857 Update finding-places-world-historical-gazetteer.md
  en/lessons/finding-places-world-historical-gazetteer.md
Labels: Lesson Maintenance, english

#2860 remove english sentence in french version of the editors guidelines
  fr/consignes-redacteurs.md
Labels: technical

#2863 Issue 2862
  en/lessons/creating-network-diagrams-from-historical-sources.md
  es/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas.md
Labels: Lesson Maintenance, spanish, english

#2864 #2816
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: Communication

#2861 Publish Reutilisation de code et modularite
  es/lecciones/reutilizacion-de-codigo-y-modularidad.md
  fr/lecons/reutilisation-de-code-et-modularite.md
Labels: translation, french
