Repository programminghistorian/jekyll, pull requests merged in 2023-09, with the labels that each got.

#3015 Issue 3014
  _data/teamroles.yml
  _includes/project-team-loop.html
Labels: ProgHist

#3025 Update descarga-automatizada-con-wget.md and creacion-de-aplicacion-shiny.md
  es/lecciones/creacion-de-aplicacion-shiny.md
  es/lecciones/descarga-automatizada-con-wget.md
Labels: Lesson Maintenance, Español

#3027 Issue 3026
  _data/ph_authors.yml
  _posts/2023-09-14-charlotte-welcome.md
Labels: ProgHist

#3020 Publish du html a une liste de mots (partie 1)
  fr/lecons/du-html-a-une-liste-de-mots-1.md
Labels: Translation, Français

#3029 Update consignes-auteurs.md
  fr/consignes-auteurs.md
Labels: Français, Guidelines

#3035 Publish analyse donnees tabulaires r
  _data/ph_authors.yml
  fr/lecons/analyse-donnees-tabulaires-R.md
  images/r-basics-with-tabular-data/fr-tr-analyse-donnees-tabulaires-R-1.png
  images/r-basics-with-tabular-data/fr-tr-analyse-donnees-tabulaires-R-2.png
Labels: Translation, Français
