Repository programminghistorian/jekyll, pull requests merged in 2023-11, with the labels that each got.

#3060 Issue 3006
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Español, Français, English, ProgHist, Português, Research

#3053 Issue 3052
  _data/ph_authors.yml
  assets/corpus-analysis-with-spacy/corpus-analysis-with-spacy-16.html
  assets/corpus-analysis-with-spacy/corpus-analysis-with-spacy-17.html
  assets/corpus-analysis-with-spacy/corpus-analysis-with-spacy-20.html
  assets/corpus-analysis-with-spacy/corpus-analysis-with-spacy.ipynb
  assets/corpus-analysis-with-spacy/metadata.csv
  assets/corpus-analysis-with-spacy/txt_files.zip
  en/lessons/corpus-analysis-with-spacy.md
  gallery/corpus-analysis-with-spacy.png
  gallery/originals/corpus-analysis-with-spacy-original.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-01.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-02.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-03.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-04.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-05.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-06.png
  images/corpus-analysis-with-spacy/or-en-corpus-analysis-with-spacy-07.png
Labels: English

#3046 Publicar Criando uma aplicação Web interativa com R e Shiny
  images/shiny-leaflet-newspaper-map-tutorial/pt-tr-aplicacao-web-interativa-r-shiny-leaflet-01.png
  images/shiny-leaflet-newspaper-map-tutorial/pt-tr-aplicacao-web-interativa-r-shiny-leaflet-02.png
  images/shiny-leaflet-newspaper-map-tutorial/pt-tr-aplicacao-web-interativa-r-shiny-leaflet-03.png
  images/shiny-leaflet-newspaper-map-tutorial/pt-tr-aplicacao-web-interativa-r-shiny-leaflet-04.gif
  images/shiny-leaflet-newspaper-map-tutorial/pt-tr-aplicacao-web-interativa-r-shiny-leaflet-05.png
  images/shiny-leaflet-newspaper-map-tutorial/pt-tr-aplicacao-web-interativa-r-shiny-leaflet-06.gif
  pt/licoes/aplicacao-web-interativa-r-shiny-leaflet.md
Labels: Translation, Português

#3049 Issue 3048
  en/individual.md
  es/donaciones.md
  fr/dons.md
  pt/doacoes.md
Labels: Community, ProgHist

#3065 Update creacion-de-aplicacion-shiny.md
  es/lecciones/creacion-de-aplicacion-shiny.md
Labels: Lesson Maintenance, Español

#3062 Publish du-html-a-une-liste-de-mots-2
  fr/lecons/du-html-a-une-liste-de-mots-2.md
Labels: Translation, Français

#3068 Issue 3067
  en/lessons/text-mining-with-extracted-features.md
Labels: Lesson Maintenance, English

#3075 Update ph_authors.yml
  _data/ph_authors.yml
Labels: Français, ProgHist

#3073 Issue 3072
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: English

#3077 Update image-classification-neural-networks.md
  en/lessons/image-classification-neural-networks.md
Labels: Lesson Maintenance, English

#3070 Issue 3069
  _posts/2023-11-15-en-call-for-lessons.md
  assets/forms/Lesson.Query.Form.txt
Labels: English

#3081 Issue 3080
  _posts/2023-11-15-en-call-for-lessons.md
  assets/forms/Lesson.Query.Form.txt
Labels: English

#3083 Update text-mining-with-extracted-features.md
  en/lessons/text-mining-with-extracted-features.md
Labels: Lesson Maintenance, English

#3085 Upload PH Banner
  images/logos/ph-4-logos-simple-banner.png
Labels: ProgHist

#3089 Issue 3088
  es/lecciones/reutilizando-colecciones-digitales-glam-labs.md
Labels: Lesson Maintenance, Español

#3091 Update introduccion-datos-abiertos-enlazados.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
Labels: Lesson Maintenance, Español

#3093 Upload bulletin banner
  images/blog/ph-bulletin-banner.png
  images/blog/ph-bulletin-banner.svg
Labels: ProgHist

#3095 New Lesson: Add analisis-redes-sociales-teatro-1
  _data/ph_authors.yml
  assets/analisis-redes-sociales-teatro-1/BizarriasDeBelisa.txt
  assets/analisis-redes-sociales-teatro-1/aristas-coaparicion_bizarrias.csv
  assets/analisis-redes-sociales-teatro-1/aristas-interaccion_bizarrias.csv
  assets/analisis-redes-sociales-teatro-1/datos_bizarrias-easylinavis.csv
  assets/analisis-redes-sociales-teatro-1/datos_bizarrias-easylinavis.txt
  assets/analisis-redes-sociales-teatro-1/nodos_bizarrias.csv
  assets/analisis-redes-sociales-teatro-1/plantilla-datos_bizarrias-ListaDeAristas.csv
  assets/analisis-redes-sociales-teatro-1/plantilla-datos_bizarrias-ListaDeNodos.csv
  assets/analisis-redes-sociales-teatro-1/plantilla-datos_bizarrias-MatrizDeAdyacencia.csv
  assets/analisis-redes-sociales-teatro-1/plantilla-datos_bizarrias.ods
  es/lecciones/analisis-redes-sociales-teatro-1.md
  gallery/analisis-redes-sociales-teatro-1.png
  gallery/originals/analisis-redes-sociales-teatro-1-original.png
  images/analisis-redes-sociales-teatro-1/es-or-analisis-redes-sociales-teatro-1-01.png
  images/analisis-redes-sociales-teatro-1/es-or-analisis-redes-sociales-teatro-1-02.png
  images/analisis-redes-sociales-teatro-1/es-or-analisis-redes-sociales-teatro-1-03.png
Labels: Español

#3097 New lesson: analisis-redes-sociales-teatro-2
  es/lecciones/analisis-redes-sociales-teatro-2.md
  gallery/analisis-redes-sociales-teatro-2.png
  gallery/originals/analisis-redes-sociales-teatro-2-original.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-01.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-02.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-03.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-04.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-05.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-06.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-07.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-08.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-09.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-10.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-11.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-12.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-13.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-14.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-15.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-16.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-17.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-18.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-19.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-20.png
  images/analisis-redes-sociales-teatro-2/es-or-analisis-redes-sociales-teatro-2-21.png
Labels: Español
