Repository programminghistorian/jekyll, pull requests merged in 2023-01, with the labels that each got.

#2814 Update link to /assets in introduccion-al-web-scraping-usando-r
  es/lecciones/introduccion-al-web-scraping-usando-r.md
Labels: Lesson Maintenance, spanish

#2811 Issue 2810
  en/lessons/geoparsing-text-with-edinburgh.md
  images/geoparsing-text-with-edinburgh/geoparser_figure01.png
  images/geoparsing-text-with-edinburgh/geoparser_figure02.png
  images/geoparsing-text-with-edinburgh/geoparser_figure13.png
  images/geoparsing-text-with-edinburgh/geoparser_figure14.png
  images/geoparsing-text-with-edinburgh/geoparser_figure15.png
  images/geoparsing-text-with-edinburgh/geoparser_figure16.png
  images/geoparsing-text-with-edinburgh/geoparser_figure17.png
Labels: Lesson Maintenance, english

#2807 Update introduccion-al-web-scraping-usando-r.md
  es/lecciones/introduccion-al-web-scraping-usando-r.md
Labels: spanish, ProgHist Ltd

#2819 Issue 2818
  pt/contribua.md
  pt/directrizes-editor.md
  pt/directrizes-tradutor.md
Labels: portuguese

#2821 Issue 2772
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication

#2815 Issue 2812
  en/lessons/detecting-text-reuse-with-passim.md
  fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.md
Labels: Lesson Maintenance, french, english

#2827 Update consignes-auteurs.md
  fr/consignes-auteurs.md
Labels: french, guidelines-update

#2823 Issue 2274
  pt/directrizes-autor.md
  pt/directrizes-tradutor.md
Labels: portuguese, guidelines-update

#2825 Issue 2824
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Communication, ProgHist Ltd

#2833 Issue 2832
  en/editor-guidelines.md
  es/guia-editor.md
  fr/consignes-redacteurs.md
  pt/directrizes-editor.md
Labels: spanish, french, english, portuguese

#2835 Issue 2834
  en/author-guidelines.md
  en/editor-guidelines.md
  es/guia-editor.md
  fr/consignes-redacteurs.md
  pt/directrizes-editor.md
Labels: technical, translation

#2831 Issue 2828
  en/lessons/automated-downloading-with-wget.md
  es/lecciones/descarga-automatizada-con-wget.md
Labels: Lesson Maintenance, spanish, english

#2838 Issue 2820
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
Labels: ProgHist Ltd

#2839 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ProgHist Ltd
