Repository programminghistorian/jekyll, pull requests merged in 2023-04, with the labels that each got.

#2905 drafting syuzhet translated lesson for publication
  assets/sentiment-analysis-syuzhet/galdos_miau.txt
  en/lessons/sentiment-analysis-syuzhet.md
  images/analisis-de-sentimientos-r/tr-en-analisis-de-sentimientos-r-1.png
  images/analisis-de-sentimientos-r/tr-en-analisis-de-sentimientos-r-2.png
  images/analisis-de-sentimientos-r/tr-en-analisis-de-sentimientos-r-3.png
Labels: english

#2918 Update ph_authors.yml
  _data/ph_authors.yml
  avatars/alexandre-wauthier.png
Labels: french

#2919 Update computer-vision-deep-learning-pt1.md
  en/lessons/computer-vision-deep-learning-pt1.md
Labels: Lesson Maintenance, english

#2920 Issue 2913
  en/about.md
  es/acerca-de.md
  fr/apropos.md
  pt/sobre.md
Labels: spanish, french, english, ProgHist Ltd, portuguese

#2922 New Translation: Creación de aplicaciones web interactivas con R y Shiny
  assets/creacion-de-aplicacion-shiny/bne_hemeroteca-digital.csv
  assets/creacion-de-aplicacion-shiny/listado-longitud-latitud-municipios-espana.csv
  assets/creacion-de-aplicacion-shiny/readme.md
  es/lecciones/creacion-de-aplicacion-shiny.md
  images/shiny-leaflet-newspaper-map-tutorial/es-tr-creacion-de-aplicacion-shiny-1.png
  images/shiny-leaflet-newspaper-map-tutorial/es-tr-creacion-de-aplicacion-shiny-2.png
  images/shiny-leaflet-newspaper-map-tutorial/es-tr-creacion-de-aplicacion-shiny-3.png
  images/shiny-leaflet-newspaper-map-tutorial/es-tr-creacion-de-aplicacion-shiny-4.gif
  images/shiny-leaflet-newspaper-map-tutorial/es-tr-creacion-de-aplicacion-shiny-5.png
  images/shiny-leaflet-newspaper-map-tutorial/es-tr-creacion-de-aplicacion-shiny-6.gif
Labels: spanish

#2925 Forgot to add R as a topic on this lesson
  en/lessons/shiny-leaflet-newspaper-map-tutorial.md
  es/lecciones/creacion-de-aplicacion-shiny.md
Labels: enhancement

#2929 Issue 2928
  en/about.md
  pt/sobre.md
Labels: ProgHist Ltd

#2930 Update installing-omeka.md
  en/lessons/installing-omeka.md
Labels: Lesson Maintenance, english

#2931 Issue 2612
  en/author-guidelines.md
  es/guia-para-autores.md
  fr/consignes-auteurs.md
  pt/directrizes-autor.md
Labels: guidelines-update

#2933 Issue 2932
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: Events
