Repository programminghistorian/jekyll, pull requests merged in 2023-06, with the labels that each got.

#2959 Issue 2956 issue 2957
  _data/ph_authors.yml
  avatars/david-valentine.png
  avatars/emilien-schultz.png
Labels: Français

#2969 Issue 2968
  es/lecciones/administracion-de-datos-en-r.md
  es/lecciones/introduccion-a-tei-2.md
Labels: Lesson Maintenance, Español

#2974 Fix broken links
  en/lessons/common-similarity-measures.md
  en/lessons/jupyter-notebooks.md
  fr/lecons/introduction-aux-carnets-jupyter-notebooks.md
Labels: Lesson Maintenance, Français, English

#2972 Issue 2962
  en/events.md
  es/eventos.md
  fr/manifestations.md
  pt/eventos.md
Labels: ProgHist, Events

#2964 Issue 2963
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#2967 Issue 2966
  en/vacancies.md
  es/vacantes.md
  fr/postes-vacants.md
  pt/vagas.md
Labels: ProgHist

#2971 Issue 2965
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
  researchpapers/Informe_final_Talleres EHCN_2023-ENG_PH.pdf
Labels: ProgHist, Research

#2976 Update finding-places-world-historical-gazetteer.md
  en/lessons/finding-places-world-historical-gazetteer.md
Labels: Lesson Maintenance, English

#2977 Update displaying-georeferenced-map-knightlab-storymap-js.md
  en/lessons/displaying-georeferenced-map-knightlab-storymap-js.md
Labels: Lesson Maintenance, English

#2979 Issue 2978
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Lesson Maintenance, ProgHist

#2981 Upload jennifer-isasi.png
  avatars/jennifer-isasi.png
Labels: ProgHist

#2958 Publicar introducao-jupyter-notebooks
  images/jupyter-notebooks/tr-pt-introducao-jupyter-notebooks-1.png
  images/jupyter-notebooks/tr-pt-introducao-jupyter-notebooks-2.png
  images/jupyter-notebooks/tr-pt-introducao-jupyter-notebooks-3.png
  images/jupyter-notebooks/tr-pt-introducao-jupyter-notebooks-4.png
  images/jupyter-notebooks/tr-pt-introducao-jupyter-notebooks-5.png
  pt/licoes/introducao-jupyter-notebooks.md
Labels: Translation, Português
