Repository programminghistorian/jekyll, pull requests merged in 2024-07, with the labels that each got.

#3305 Update visualizing-with-bokeh.md
  en/ipp.md
  en/lessons/visualizing-with-bokeh.md
  en/supporters.md
  es/colaboradores.md
  es/pia.md
  fr/nos-soutiens.md
  fr/pi.md
  pt/apoiadores.md
  pt/ppi.md
Labels: Lesson Maintenance, English

#3309 Create TEST-colab-notebook.ipynb
  assets/TEST-colab-notebook/TEST-colab-notebook.ipynb
Labels: Technical

#3303 Preparing Appel à contributions (édition française)
  _data/ph_authors.yml
  _posts/2024-07-04-appel-a-contributions.md
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/formulaire-lecon.txt
  fr/consignes-auteurs.md
Labels: Français

#3315 Update working-with-batches-of-pdf-files.md
  en/lessons/working-with-batches-of-pdf-files.md
Labels: Lesson Maintenance, English

#3313 Issue 3312
  en/individual.md
  es/donaciones.md
  fr/dons.md
  pt/doacoes.md
Labels: ProgHist

#3317 Issue 3316 a
  assets/TEST-colab-notebook/TEST-colab-notebook.ipynb
  assets/computer-vision-deep-learning-pt1-2/computer-vision-deep-learning-pt1-2.ipynb
  assets/computer-vision-deep-learning-pt1/computer-vision-deep-learning-pt1-2.ipynb
  assets/understanding-creating-word-embeddings/understanding-creating-word-embeddings.ipynb
Labels: Lesson Maintenance

#3321 Issue 3320
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#3327 Update introduction-to-populating-a-website-with-api-data.md
  en/lessons/introduction-to-populating-a-website-with-api-data.md
Labels: Lesson Maintenance, English

#3330 Issue 3329
  en/lessons/extracting-illustrated-pages.md
  pt/licoes/extrair-paginas-ilustradas-com-python.md
Labels: Lesson Maintenance, English, Português

#3324 Preparing to launch a new expression of interest form for Peer Reviewers (EN, ES, FR)
  assets/forms/en-ph-peer-review-form.txt
  assets/forms/es-ph-revisión-por-pares-formulario.txt
  assets/forms/fr-ph-evaluation-par-les-pairs-formulaire.txt
  en/contribute.md
  es/contribuciones.md
  fr/contribuer.md
Labels: Español, Français, English
