Repository programminghistorian/jekyll, pull requests merged in 2024-12, with the labels that each got.

#3401 Issue 3396
  en/lessons/windows-installation.md
  es/lecciones/instalacion-windows.md
  fr/lecons/installation-windows-py.md
  pt/licoes/instalacao-windows.md
Labels: Lesson Maintenance, Español, Français, English, Português

#3419 Issue 3418
  en/lessons/transforming-xml-with-xsl.md
  en/lessons/using-javascript-to-create-maps.md
  es/lecciones/transformacion-datos-xml-xsl.md
Labels: Lesson Maintenance, Español, English

#3421 Publish es/uso-las-colecciones-hathitrust-mineria-textual-R
  _data/ph_authors.yml
  assets/uso-las-colecciones-hathitrust-mineria-textual-R/100_Novelas_de_Ecuador.tsv
  assets/uso-las-colecciones-hathitrust-mineria-textual-R/ciudades.xls
  assets/uso-las-colecciones-hathitrust-mineria-textual-R/fechas.xls
  assets/uso-las-colecciones-hathitrust-mineria-textual-R/obtener_tokens.r
  es/lecciones/uso-las-colecciones-hathitrust-mineria-textual-R.md
  gallery/originals/uso-las-colecciones-hathitrust-mineria-textual-R-original.jpg
  gallery/uso-las-colecciones-hathitrust-mineria-textual-R.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-01.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-02.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-03.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-04.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-05.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-06.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-07.png
  images/uso-las-colecciones-hathitrust-mineria-textual-R/es-or-uso-las-colecciones-hathitrust-mineria-textual-R-08.png
Labels: Español

#3422 Issue 3359
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Español, Français, English, ProgHist, Português, Research

#3424 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Community, ProgHist

#3409 Publish pt/licoes/introducao-linha-comando-bash
  pt/licoes/introducao-linha-comando-bash.md
Labels: Português

#3428 Publish es/lecciones/georreferenciacion-visualizacion-con-recogito-y-visone
  _data/ph_authors.yml
  assets/georreferenciacion-visualizacion-con-recogito-y-visone/fragmento_La_Argentina_manuscrita_tutorial_recogito_visone.txt
  assets/georreferenciacion-visualizacion-con-recogito-y-visone/lugares-marcados.csv
  es/lecciones/georreferenciacion-visualizacion-con-recogito-y-visone.md
  gallery/georreferenciacion-visualizacion-con-recogito-y-visone.png
  gallery/originals/georreferenciacion-visualizacion-con-recogito-y-visone-original.png
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-01.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-02.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-03.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-04.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-05.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-06.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-07.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-08.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-09.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-10.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-11.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-12.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-13.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-14.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-15.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-16.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-17.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-18.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-19.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-20.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-21.jpg
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-22.jpg
Labels: Español

#3433 Issue 3432
  fr/lecons/preserver-logiciels-recherche.md
Labels: Lesson Maintenance, Français

#3431 Issue 3426 Publish Bulletin 05
  _posts/2024-12-13-bulletin-issue-05.md
  assets/bulletin/2024-12-13-bulletin-issue-05.pdf
Labels: Community, ProgHist

#3437 Issue 3434
  _posts/2024-11-15-en-call-for-proposals.md
  en/author-guidelines.md
  en/contribute.md
Labels: English, Community, ProgHist

#3436 Issue 3425
  en/lessons/cleaning-data-with-openrefine.md
  en/lessons/intro-to-linked-data.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
  es/lecciones/limpieza-de-datos-con-OpenRefine.md
  fr/lecons/nettoyer-ses-donnees-avec-openrefine.md
  pt/licoes/introducao-dados-abertos-conectados.md
  pt/licoes/limpar-dados-openrefine.md
Labels: Lesson Maintenance, Español, Français, English, Português

#3438 Issue 3432
  fr/lecons/preserver-logiciels-recherche.md
Labels: Lesson Maintenance, Français
