Repository programminghistorian/jekyll, pull requests merged in 2024-01, with the labels that each got.

#3137 Issue 3136
  en/lessons/intro-to-twitterbots.md
  fr/lecons/intro-aux-bots-twitter.md
Labels: Lesson Maintenance, Français, English

#3141 Issue 3140
  _posts/2023-11-15-en-call-for-lessons.md
Labels: English

#3135 Update ph_authors.yml
  _data/ph_authors.yml
Labels: Português

#3145 Update geospatial-data-analysis.md
  en/lessons/clustering-visualizing-word-embeddings.md
  en/lessons/geospatial-data-analysis.md
Labels: Lesson Maintenance, English

#3143 Update ph_authors.yml
  _data/ph_authors.yml
Labels: Français

#3153 Update creating-mobile-augmented-reality-experiences-in-unity.md
  en/lessons/creating-mobile-augmented-reality-experiences-in-unity.md
Labels: Lesson Maintenance, English

#3155 Issue 3154
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Español, Français, English, Português, Research

#3157 Issue 3156
  _data/snippets.yml
  assets/forms/Formulaire.Tutoriel.txt
  assets/forms/Formulario.Consulta.Leccion.txt
  assets/forms/formulario.proposta.licao.txt
Labels: ProgHist, Português

#3150 Publish /en/lessons/understanding-creating-word-embeddings
  _data/ph_authors.yml
  en/lessons/understanding-creating-word-embeddings.md
  gallery/originals/understanding-creating-word-embeddings-original.png
  gallery/understanding-creating-word-embeddings.png
Labels: English

#3159 Update understanding-creating-word-embeddings.md
  en/lessons/understanding-creating-word-embeddings.md
Labels: English
