Repository programminghistorian/jekyll, pull requests merged in 2024-10, with the labels that each got.

#3364 Issue 3363
  en/lessons/beginners-guide-to-twitter-data.md
  en/lessons/data-wrangling-and-management-in-R.md
  en/lessons/geospatial-data-analysis.md
  en/lessons/sentiment-analysis-syuzhet.md
  en/lessons/shiny-leaflet-newspaper-map-tutorial.md
  es/lecciones/administracion-de-datos-en-r.md
  gallery/data-wrangling-and-management-in-R.png
  gallery/originals/data-wrangling-and-management-in-R-original.png
  images/data-wrangling-and-management-in-R/en-or-data-wrangling-and-management-in-R-01.png
  images/data-wrangling-and-management-in-R/en-or-data-wrangling-and-management-in-R-02.png
  images/data-wrangling-and-management-in-R/en-or-data-wrangling-and-management-in-R-03.png
  images/data-wrangling-and-management-in-R/en-or-data-wrangling-and-management-in-R-04.png
  images/data-wrangling-and-management-in-R/es-tr-administracion-de-datos-en-r-01.png
  images/data-wrangling-and-management-in-R/es-tr-administracion-de-datos-en-r-02.png
  images/data-wrangling-and-management-in-R/es-tr-administracion-de-datos-en-r-03.png
  images/data-wrangling-and-management-in-R/es-tr-administracion-de-datos-en-r-04.png
  images/data-wrangling-and-management-in-R/pt-tr-manipulacao-transformacao-dados-R-01.png
  images/data-wrangling-and-management-in-R/pt-tr-manipulacao-transformacao-dados-R-02.png
  images/data-wrangling-and-management-in-R/pt-tr-manipulacao-transformacao-dados-R-03.png
  images/data-wrangling-and-management-in-R/pt-tr-manipulacao-transformacao-dados-R-04.png
  pt/licoes/analise-sentimento-R-syuzhet.md
  pt/licoes/manipulacao-transformacao-dados-R.md
  pt/licoes/visualizacao-animacao-tabelas-historicas-R.md
Labels: Lesson Maintenance, Español, English, Português

#3379 Issue 3378
  es/lecciones/editar-audio-con-audacity.md
Labels: Lesson Maintenance, Español

#3373 Issue 3372
  en/lessons/geocoding-qgis.md
Labels: Lesson Maintenance, English

#3375 Issue 3374
  _posts/2024-09-27-bulletin-issue-04.md
Labels: Community, ProgHist

#3381 Issue 3359
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: ProgHist, Research

#3380 Issue 3367
  en/lessons/working-with-batches-of-pdf-files.md
Labels: Lesson Maintenance, English

#3377 Issue 3376
  en/ipp.md
  en/supporters.md
  es/colaboradores.md
  es/pia.md
  fr/nos-soutiens.md
  fr/pi.md
  pt/apoiadores.md
  pt/ppi.md
Labels: Community, ProgHist

#3385 Publish /es/lecciones/lectura-escalable-de-datos-estructurados
  _data/ph_authors.yml
  es/lecciones/lectura-escalable-de-datos-estructurados.md
  images/scalable-reading-of-structured-data/lectura-escalable-de-datos-estructurados-1.png
  images/scalable-reading-of-structured-data/lectura-escalable-de-datos-estructurados-2.png
  images/scalable-reading-of-structured-data/lectura-escalable-de-datos-estructurados-3.png
Labels: Español

#3389 Remove broken link in /es/lecciones/introduccion-a-tei-1
  es/lecciones/introduccion-a-tei-1.md
Labels: Lesson Maintenance, Español

#3390 Update introducao-codificacao-textos-tei-1.md
  pt/licoes/introducao-codificacao-textos-tei-1.md
Labels: Lesson Maintenance, Português

#3350 Publish fr/lecons/normaliser-donnees-textuelles-python
  assets/normaliser-donnees-textuelles-python/obo-t17800628-33.html
  fr/lecons/normaliser-donnees-textuelles-python.md
Labels: Français

#3391 Upload `.ipynb` for /en/lesson/analyzing-multilingual-text-nltk-spacy-stanza
  assets/analyzing-multilingual-text-nltk-spacy-stanza/analyzing-multilingual-text-nltk-spacy-stanza.ipynb
Labels: English
