Repository programminghistorian/jekyll, pull requests merged in 2024-06, with the labels that each got.

#3276 Update introduccion-a-imageplot-y-la-visualizacion-de-metadatos.md
  es/lecciones/introduccion-a-imageplot-y-la-visualizacion-de-metadatos.md
Labels: Lesson Maintenance, Español

#3274 Publish pt/licoes/download-automatico-wget
  pt/licoes/download-automatico-wget.md
Labels: Português

#3280 Issue 3279
  en/events.md
  en/research.md
  es/eventos.md
  es/investigacion.md
  fr/evenements.md
  fr/recherche.md
  pt/eventos.md
  pt/pesquisa.md
Labels: Events, Research

#3282 Issue 3281
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#3286 Update finding-places-world-historical-gazetteer.md
  en/lessons/finding-places-world-historical-gazetteer.md
Labels: Lesson Maintenance, English

#3284 Update logistic-regression.md
  en/lessons/logistic-regression.md
Labels: Lesson Maintenance, English

#3287 Update sitios-estaticos-con-jekyll-y-github-pages.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
Labels: Lesson Maintenance, Español

#3294 Issue 3270
  en/events.md
  en/research.md
  es/eventos.md
  es/investigacion.md
  fr/evenements.md
  fr/recherche.md
  pt/eventos.md
  pt/pesquisa.md
Labels: ProgHist, Research

#3297 Update ph_authors.yml
  _data/ph_authors.yml
Labels: ProgHist

#3301 Issue 3300
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: ProgHist

#3299 Issue 3298
  _posts/2024-06-28-bulletin-issue-03.md
  assets/bulletin/2024-06-28-bulletin-issue-03.pdf
  images/blog/250-lessons.png
Labels: Community, ProgHist
