Repository programminghistorian/jekyll, pull requests merged in 2024-03, with the labels that each got.

#3183 Issue 3175
  en/ipp.md
  es/pia.md
  fr/pi.md
  pt/ppi.md
Labels: ProgHist

#3196 Issue 3195
  en/events.md
  en/research.md
  es/eventos.md
  es/investigacion.md
  fr/evenements.md
  fr/recherche.md
  pt/eventos.md
  pt/pesquisa.md
Labels: Events

#3198 Issue 3197
  en/contribute.md
Labels: English, ProgHist

#3200 Issue 3199
  _posts/2024-03-07-Open-Education-Week.md
  images/blog/OEW-banner.jpg
Labels: Community, ProgHist, Events

#3202 Issue-3201
  _posts/2024-03-07-Open-Education-Week.md
Labels: ProgHist

#3206 Issue-3160-c
  en/lessons/clustering-visualizing-word-embeddings.md
Labels: Lesson Maintenance, English

#3204 Prepação para publicação da tradução Reconhecimento automático de manuscritos para o teste de idiomas não latinos
  pt/licoes/transcricao-automatica-grafias-nao-latinas.md
Labels: Português

#3214 Update finding-places-world-historical-gazetteer.md
  en/lessons/finding-places-world-historical-gazetteer.md
Labels: Lesson Maintenance, English

#3211 Publish fr/lecons/demarrer-avec-omeka-classic
  _data/ph_authors.yml
  fr/lecons/demarrer-avec-omeka-classic.md
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-05.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-07.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-08.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-09.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-10.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-11.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-12.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-13.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-14.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-15.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-16.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-17.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-18.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-19.png
  images/up-and-running-with-omeka/fr-tr-demarrer-avec-omeka-classic-20.png
Labels: Français

#3216 Issue 3215
  en/lessons/cleaning-data-with-openrefine.md
  es/lecciones/limpieza-de-datos-con-OpenRefine.md
  fr/lecons/nettoyer-ses-donnees-avec-openrefine.md
  pt/licoes/limpar-dados-openrefine.md
Labels: Lesson Maintenance, Español, Français, English, Português

#3218 Publish /en/lessons/space-place-gazetteers
  _data/ph_authors.yml
  assets/space-place-gazetteers/TudelaGazetteer.xlsx
  assets/space-place-gazetteers/TudelaGazetteerModernNames.xlsx
  en/lessons/space-place-gazetteers.md
  gallery/originals/space-place-gazetteers-original.png
  gallery/space-place-gazetteers.png
  images/space-place-gazetteers/en-or-space-place-gazetteers-01.jpg
  images/space-place-gazetteers/en-or-space-place-gazetteers-02.jpg
Labels: English

#3222 Issue 3221
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#3171 Issue 2840
  en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md
  fr/lecons/redaction-durable-avec-pandoc-et-markdown.md
  pt/licoes/autoria-sustentavel-texto-simples-pandoc-markdown.md
Labels: Lesson Maintenance, Español, Français, English, Português

#3228 Issue 3227
  _posts/2024-03-27-bulletin-issue-02.md
  assets/bulletin/2024-03-27-bulletin-issue-02.pdf
Labels: Community, ProgHist

#3230 Upload replacement 2024-03-27-bulletin-issue-02.pdf
  assets/bulletin/2024-03-27-bulletin-issue-02.pdf
Labels: ProgHist

#3224 Issue-3223
  en/lessons/cleaning-ocrd-text-with-regular-expressions.md
Labels: Lesson Maintenance, English

#3233 Update ph_authors.yml
  _data/ph_authors.yml
Labels: English, Community, ProgHist

#3236 Update ph_authors.yml
  _data/ph_authors.yml
Labels: English, Community, ProgHist

#3234 Update ph_authors.yml
  _data/ph_authors.yml
Labels: Français, Community, ProgHist
