Repository programminghistorian/jekyll, pull requests merged in 2025-03, with the labels that each got.

#3486 Update qgis-camadas.md
  pt/licoes/qgis-camadas.md
Labels: Lesson Maintenance, Português

#3490 Issue-3489-texas-link
  es/lecciones/exhibicion-con-collection-builder.md
Labels: Lesson Maintenance, Español

#3494 Issue-3493-tested-date
  en/lessons/creating-an-omeka-exhibit.md
  en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
  en/lessons/up-and-running-with-omeka.md
  pt/licoes/autoria-sustentavel-texto-simples-pandoc-markdown.md
Labels: Lesson Maintenance

#3500 Issue-3499-guidelines-link
  es/lecciones/introduccion-a-tei-1.md
  pt/licoes/introducao-codificacao-textos-tei-1.md
Labels: Lesson Maintenance, Español, Português

#3498 Issue-3496-figure-5
  images/georreferenciacion-visualizacion-con-recogito-y-visone/es-or-georreferenciacion-visualizacion-con-recogito-y-visone-05.jpg
Labels: Lesson Maintenance, Español

#3502 Issue 3501
  en/lessons/geocoding-qgis.md
  en/lessons/georeferencing-qgis.md
  en/lessons/googlemaps-googleearth.md
  en/lessons/qgis-layers.md
  en/lessons/vector-layers-qgis.md
  es/lecciones/analisis-redes-sociales-teatro-1.md
  es/lecciones/analisis-redes-sociales-teatro-2.md
  es/lecciones/introduccion-a-tei-1.md
  es/lecciones/introduccion-a-tei-2.md
  fr/lecons/du-html-a-une-liste-de-mots-1.md
  fr/lecons/du-html-a-une-liste-de-mots-2.md
  pt/licoes/HTML-lista-palavras-1.md
  pt/licoes/HTML-lista-palavras-2.md
Labels: Lesson Maintenance, Español, Technical, Français, English, Português

#3492 Issue-3491-intro-linked-data
  en/lessons/intro-to-linked-data.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
  pt/licoes/introducao-dados-abertos-conectados.md
Labels: Lesson Maintenance, Español, English, Português

#3505 Issue-3504-atom-sunset
  es/lecciones/publicar-archivos-tei-ceteicean.md
Labels: Lesson Maintenance, Español

#3508 Issue 3507 jisc
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: ProgHist

#3512 Issue-3511-b
  en/lessons/cleaning-data-with-openrefine.md
  es/lecciones/limpieza-de-datos-con-OpenRefine.md
  fr/lecons/nettoyer-ses-donnees-avec-openrefine.md
Labels: Lesson Maintenance, Español, Français, English

#3518 Issue-3515-map-warper-images
  en/lessons/introduction-map-warper.md
  es/lecciones/introduccion-map-warper.md
  images/introduccion-map-warper/Add_Control_II.png
  images/introduccion-map-warper/Control_points.png
  images/introduccion-map-warper/Crop_1.JPG
  images/introduccion-map-warper/Crop_1a.JPG
  images/introduccion-map-warper/Draw_new_polygon.gif
  images/introduccion-map-warper/Draw_polygon.gif
  images/introduccion-map-warper/VARIOS1.gif
  images/introduccion-map-warper/VARIOS2.gif
  images/introduccion-map-warper/Warp_imagen.png
  images/introduccion-map-warper/Zoom_lock.png
  images/introduccion-map-warper/add custom base map.png
  images/introduccion-map-warper/add_control_point.gif
  images/introduccion-map-warper/add_custom_basemap.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-01.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-02.gif
  images/introduccion-map-warper/en-tr-introduction-map-warper-03.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-04.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-05.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-06.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-07.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-08.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-09.png
  images/introduccion-map-warper/en-tr-introduction-map-warper-10.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-01.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-02.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-03.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-04.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-05.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon1.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon10.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon11.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon12.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon2.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon3.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon4.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon5.gif
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon6.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon7.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon8.png
  images/introduccion-map-warper/es-or-introduccion-map-warper-icon9.png
  images/introduccion-map-warper/fmapoteca_984_figac_16.jpg
  images/introduccion-map-warper/imagenes.md
  images/introduccion-map-warper/move around map.gif
  images/introduccion-map-warper/move_control_point.gif
  images/introduccion-map-warper/move_map.gif
  images/introduccion-map-warper/rss.png
Labels: Lesson Maintenance, Español, English

#3510 Publish en/lessons/urban-demographic-data-r-ggplot2
  _data/ph_authors.yml
  assets/urban-demographic-data-r-ggplot2/sistercities.csv
  en/lessons/urban-demographic-data-r-ggplot2.md
  gallery/originals/urban-demographic-data-r-ggplot2-original.jpg
  gallery/urban-demographic-data-r-ggplot2.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-01.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-02.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-03.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-04.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-05.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-06.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-07.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-08.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-09.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-10.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-11.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-12.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-13.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-14.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-15.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-16.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-17.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-18.png
  images/urban-demographic-data-r-ggplot2/en-or-urban-demographic-data-r-ggplot2-19.png
Labels: English

#3517 Publish en/lessons/interactive-data-visualization-dashboard
  _data/ph_authors.yml
  en/lessons/interactive-data-visualization-dashboard.md
  gallery/interactive-data-visualization-dashboard.png
  gallery/originals/interactive-data-visualization-dashboard-original.png
  images/interactive-data-visualization-dashboard/en-or-interactive-data-visualization-dashboard-01.png
  images/interactive-data-visualization-dashboard/en-or-interactive-data-visualization-dashboard-02.gif
  images/interactive-data-visualization-dashboard/en-or-interactive-data-visualization-dashboard-03.gif
  images/interactive-data-visualization-dashboard/en-or-interactive-data-visualization-dashboard-04.png
Labels: English

#3523 Issue-3522-bulletin-06
  _posts/2025-03-28-bulletin-issue-06.md
  assets/bulletin/2025-03-28-bulletin-issue-06.pdf
Labels: Community, ProgHist
