Repository programminghistorian/jekyll, pull requests merged in 2025-01, with the labels that each got.

#3430 Publish /fr/lecons/gestion-manipulation-donnees-r
  assets/data-wrangling-and-management-in-r/ejemplo_introductorio_estados.csv
  assets/data-wrangling-and-management-in-r/introductory_state_example.csv
  en/lessons/beginners-guide-to-twitter-data.md
  en/lessons/data-wrangling-and-management-in-r.md
  en/lessons/geospatial-data-analysis.md
  en/lessons/sentiment-analysis-syuzhet.md
  en/lessons/shiny-leaflet-newspaper-map-tutorial.md
  es/lecciones/administracion-de-datos-en-r.md
  fr/lecons/gestion-manipulation-donnees-r.md
  gallery/data-wrangling-and-management-in-r.png
  images/data-wrangling-and-management-in-r/en-or-data-wrangling-and-management-in-r-01.png
  images/data-wrangling-and-management-in-r/en-or-data-wrangling-and-management-in-r-02.png
  images/data-wrangling-and-management-in-r/en-or-data-wrangling-and-management-in-r-03.png
  images/data-wrangling-and-management-in-r/en-or-data-wrangling-and-management-in-r-04.png
  images/data-wrangling-and-management-in-r/es-tr-administracion-de-datos-en-r-01.png
  images/data-wrangling-and-management-in-r/es-tr-administracion-de-datos-en-r-02.png
  images/data-wrangling-and-management-in-r/es-tr-administracion-de-datos-en-r-03.png
  images/data-wrangling-and-management-in-r/es-tr-administracion-de-datos-en-r-04.png
  images/data-wrangling-and-management-in-r/fr-tr-gestion-manipulation-donnees-r-03.png
  images/data-wrangling-and-management-in-r/fr-tr-gestion-manipulation-donnees-r-04.png
  images/data-wrangling-and-management-in-r/pt-tr-manipulacao-transformacao-dados-r-01.png
  images/data-wrangling-and-management-in-r/pt-tr-manipulacao-transformacao-dados-r-02.png
  images/data-wrangling-and-management-in-r/pt-tr-manipulacao-transformacao-dados-r-03.png
  images/data-wrangling-and-management-in-r/pt-tr-manipulacao-transformacao-dados-r-04.png
  pt/licoes/analise-sentimento-R-syuzhet.md
  pt/licoes/aplicacao-web-interativa-r-shiny-leaflet.md
  pt/licoes/manipulacao-transformacao-dados-r.md
  pt/licoes/visualizacao-animacao-tabelas-historicas-R.md
Labels: Français

#3440 Issue 3435
  _data/topics.yml
Labels: Lesson Maintenance, Enhancement

#3450 Publish /pt/licoes/qgis-camadas
  en/lessons/qgis-layers.md
  images/qgis-layers/pt-tr-qgis-camadas-01.png
  images/qgis-layers/pt-tr-qgis-camadas-02.png
  images/qgis-layers/pt-tr-qgis-camadas-03.png
  images/qgis-layers/pt-tr-qgis-camadas-04.png
  images/qgis-layers/pt-tr-qgis-camadas-05.png
  images/qgis-layers/pt-tr-qgis-camadas-06.png
  images/qgis-layers/pt-tr-qgis-camadas-07.png
  images/qgis-layers/pt-tr-qgis-camadas-08.png
  images/qgis-layers/pt-tr-qgis-camadas-09.png
  images/qgis-layers/pt-tr-qgis-camadas-10.png
  images/qgis-layers/pt-tr-qgis-camadas-11.png
  images/qgis-layers/pt-tr-qgis-camadas-12.png
  images/qgis-layers/pt-tr-qgis-camadas-13.png
  images/qgis-layers/pt-tr-qgis-camadas-14.png
  images/qgis-layers/pt-tr-qgis-camadas-15.png
  images/qgis-layers/pt-tr-qgis-camadas-16.png
  images/qgis-layers/pt-tr-qgis-camadas-17.png
  images/qgis-layers/pt-tr-qgis-camadas-18.png
  images/qgis-layers/pt-tr-qgis-camadas-19.png
  images/qgis-layers/pt-tr-qgis-camadas-20.png
  images/qgis-layers/pt-tr-qgis-camadas-21.png
  images/qgis-layers/pt-tr-qgis-camadas-22.png
  images/qgis-layers/pt-tr-qgis-camadas-23.png
  images/qgis-layers/pt-tr-qgis-camadas-24.png
  images/qgis-layers/pt-tr-qgis-camadas-25.png
  images/qgis-layers/pt-tr-qgis-camadas-26.png
  images/qgis-layers/pt-tr-qgis-camadas-27.png
  images/qgis-layers/pt-tr-qgis-camadas-28.png
  images/qgis-layers/pt-tr-qgis-camadas-29.png
  images/qgis-layers/pt-tr-qgis-camadas-30.png
  images/qgis-layers/pt-tr-qgis-camadas-31.png
  images/qgis-layers/pt-tr-qgis-camadas-32.png
  pt/licoes/qgis-camadas.md
Labels: Português

#3449 Publish /pt/licoes/geocodificando-qgis
  assets/geocodificando-qgis/CondadosExAlunos.csv
  assets/geocodificando-qgis/Os-Dados-Alum-Oxon-Jas1-Nomes-de-Lugares.csv
  images/geocoding-qgis/pt-tr-geocodificando-qgis-01.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-02.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-03.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-04.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-05.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-06.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-07.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-08.png
  images/geocoding-qgis/pt-tr-geocodificando-qgis-09.png
  pt/licoes/geocodificando-qgis.md
Labels: Português

#3460 Issue-3459-anaconda-links
  en/lessons/common-similarity-measures.md
  en/lessons/jupyter-notebooks.md
  fr/lecons/introduction-aux-carnets-jupyter-notebooks.md
  pt/licoes/introducao-jupyter-notebooks.md
Labels: Lesson Maintenance, Français, English, Português

#3463 Issue-3462-lancaster-alumni
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: ProgHist

#3467 Update geocodificando-qgis.md
  pt/licoes/geocodificando-qgis.md
Labels: Português

#3453 Publish es/lecciones/datos-abiertos-enlazados-wikidata
  _data/ph_authors.yml
  es/lecciones/datos-abiertos-enlazados-wikidata.md
  gallery/datos-abiertos-enlazados-wikidata.png
  gallery/originals/datos-abiertos-enlazados-wikidata-original.jpg
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-01.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-02.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-03.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-04.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-05.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-06.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-07.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-08.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-09.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-10.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-11.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-12.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-13.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-14.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-15.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-16.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-17.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-18.png
  images/datos-abiertos-enlazados-wikidata/es-or-datos-abiertos-enlazados-wikidata-19.png
Labels: Español

#3469 Update datos-abiertos-enlazados-wikidata.md
  es/lecciones/datos-abiertos-enlazados-wikidata.md
Labels: Español

#3465 Issue-3464-intro-linked-data-images
  en/lessons/intro-to-linked-data.md
  es/lecciones/introduccion-datos-abiertos-enlazados.md
  images/intro-to-linked-data/create.md
  images/intro-to-linked-data/en-or-intro-to-linked-data-01.png
  images/intro-to-linked-data/en-or-intro-to-linked-data-02.png
  images/intro-to-linked-data/en-or-intro-to-linked-data-03.png
  images/intro-to-linked-data/en-or-intro-to-linked-data-04.png
  images/intro-to-linked-data/en-or-intro-to-linked-data-05.png
  images/intro-to-linked-data/en-or-intro-to-linked-data-06.png
  images/intro-to-linked-data/es-tr-intro-a-datos-enlazados-01.png
  images/intro-to-linked-data/es-tr-intro-a-datos-enlazados-02.png
  images/intro-to-linked-data/pt-tr-introducao-dados-abertos-conectados-01.png
  images/intro-to-linked-data/pt-tr-introducao-dados-abertos-conectados-02.png
  pt/licoes/introducao-dados-abertos-conectados.md
Labels: Lesson Maintenance, Español, English, Português

#3446 Publish /pt/licoes/extrair-palavras-chave
  en/lessons/extracting-keywords.md
  pt/licoes/extrair-palavras-chave.md
Labels: Português

#3472 Issue-3362-retire-OCR-lesson
  en/lessons/retired/OCR-and-Machine-Translation.md
Labels: Lesson Maintenance, English

#3476 Issue-3475-package-typo
  fr/lecons/gestion-manipulation-donnees-r.md
Labels: Lesson Maintenance, Français

#3479 update-trustees
  _data/ph_authors.yml
  avatars/adam-farquhar.png
Labels: ProgHist

#3480 Issue-3468-melvin-hersent
  _data/ph_authors.yml
  avatars/melvin-hersent.png
Labels: Community, ProgHist
