Repository programminghistorian/jekyll, pull requests merged in 2025-05, with the labels that each got.

#3543 Issue-3542-update-supporters
  en/supporters.md
  es/colaboradores.md
  fr/nos-soutiens.md
  pt/apoiadores.md
Labels: Community, ProgHist

#3535 Publish /en/lessons/calibrating-radiocarbon-dates-r
  en/lessons/calibrating-radiocarbon-dates-r.md
Labels: English

#3457 Issue-3456-topic-audit
  _data/topics.yml
  pt/licoes/git-ferramenta-metodologica-projetos-historia-1.md
Labels: Lesson Maintenance, Enhancement

#3549 Upload assets for /choropleth-maps-python-folium
  assets/choropleth-maps-python-folium/PoliceKillingsOfCivilians.html
  assets/choropleth-maps-python-folium/cb_2021_us_county_5m.zip
  assets/choropleth-maps-python-folium/choropleth-maps-python-folium.ipynb
  assets/choropleth-maps-python-folium/co-est2019-alldata.csv
  assets/choropleth-maps-python-folium/fatal-force-database-README.md
  assets/choropleth-maps-python-folium/fatal-police-shootings-data.csv
Labels: English

#3545 Publish /pt/licoes/investigar-literatura-lusofona-literateca
  assets/investigar-literatura-lusofona-literateca/distribuicaoAparenciaDecadaGen.tsv
  assets/investigar-literatura-lusofona-literateca/distribuicaoCidadesObra.tsv
  assets/investigar-literatura-lusofona-literateca/distribuicaoLocaisObra.tsv
  assets/investigar-literatura-lusofona-literateca/distribuicaoObra.tsv
  assets/investigar-literatura-lusofona-literateca/distribuicaoPredDecadaGen.tsv
  assets/investigar-literatura-lusofona-literateca/distribuicaoRoupa.tsv
  gallery/investigar-literatura-lusofona-literateca.png
  gallery/originals/investigar-literatura-lusofona-literateca-original.jpg
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-01.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-02.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-03.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-04.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-05.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-06.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-07.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-08.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-09.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-10.png
  images/investigar-literatura-lusofona-literateca/pt-or-investigar-literatura-lusofona-literateca-11.png
  pt/licoes/investigar-literatura-lusofona-literateca.md
Labels: Português

#3556 Issue 3555 links
  en/lessons/analyzing-documents-with-tfidf.md
  en/lessons/building-static-sites-with-jekyll-github-pages.md
  en/lessons/detecting-text-reuse-with-passim.md
  en/lessons/geoparsing-text-with-edinburgh.md
  en/lessons/interrogating-national-narrative-gpt.md
  en/research.md
  es/investigacion.md
  es/lecciones/sitios-estaticos-con-jekyll-y-github-pages.md
  fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Lesson Maintenance, Español, Français, English

#3563 Issue-3562-gibbs-link
  en/research.md
  es/investigacion.md
  fr/recherche.md
  pt/pesquisa.md
Labels: Lesson Maintenance, Research

#3567 Update 2015-05-17-edinburgh-workshop-2015.md
  _posts/2015-05-17-edinburgh-workshop-2015.md
Labels: Lesson Maintenance, ProgHist

#3574 Issue-3573-replace-DOIs
  en/lessons/analyzing-documents-with-tfidf.md
  en/lessons/detecting-text-reuse-with-passim.md
  en/lessons/geoparsing-text-with-edinburgh.md
  en/lessons/interrogating-national-narrative-gpt.md
  fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.md
Labels: Lesson Maintenance, Français, English
