Repository programminghistorian/jekyll, pull requests merged in 2025-06, with the labels that each got.

#3560 Publish /en/lessons/teach-history-and-languages-with-strategy-game
  _data/ph_authors.yml
  en/lessons/teach-history-and-languages-with-strategy-game.md
  gallery/originals/teach-history-and-languages-with-strategy-game-original.jpg
  gallery/teach-history-and-languages-with-strategy-game.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-01.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-02.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-03.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-04.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-05.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-06.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-07.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-08.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-09.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-10.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-11.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-12.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-13.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-14.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-15.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-16.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-17.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-18.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-19.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-20.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-21.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-22.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-23.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-24.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-25.png
  images/teach-history-and-languages-with-strategy-game/en-or-teach-history-and-languages-with-strategy-game-26.png
Labels: English

#3585 Issue-3584-clump-link
  en/lessons/vector-layers-qgis.md
  pt/licoes/camadas-vetoriais-qgis.md
Labels: Lesson Maintenance, English, Português

#3587 Publish /en/lessons/corpus-analysis-voyant-tools
  assets/corpus-analysis-voyant-tools/stopwords-en.txt
  en/lessons/corpus-analysis-voyant-tools.md
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-01.gif
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-02.gif
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-03.gif
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-04.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-05.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-06.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-07.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-08.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-09.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-10.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-11.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-12.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-13.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-14.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-15.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-16.png
  images/analisis-voyant-tools/en-tr-corpus-analysis-voyant-tools-17.png
Labels: English

#3600 Issue-3599-ggplot-link
  pt/licoes/manipulacao-transformacao-dados-r.md
Labels: Lesson Maintenance, Português

#3598 Issue-3597-bulletin-07
  _posts/2025-06-27-bulletin-issue-07.md
  assets/bulletin/2025-06-27-bulletin-issue-07.pdf
Labels: Community, ProgHist
